- .travis.yml
> Configure travis-ci

- renovate.json
This PR updates the renovate config to support our pinning strategy (similar to addons-frontend).
> Enhance renovate config

- package.json
- src/index.tsx
- yarn.lock
Fixes #24 
I tested this using an example from https://reacttraining.com/react-router/web/guides/quick-start and it seems to work. I didn't create any actual routes as we don't have any pages to serve yet.
I think we'll probably want to upgrade the router to use [connected-react-router](https://github.com/supasate/connected-react-router), but that should be done after we add redux, which I believe is coming in #6.
> Configure React Router for Create React App

- .travis.yml
- package.json
- yarn.lock
> Add codecov to CI

- package.json
- src/App.test.tsx
- src/App.tsx
- src/configureStore.tsx
- src/index.tsx
- src/reducers/example.tsx
- src/reducers/index.tsx
- yarn.lock
Fixes https://github.com/mozilla/addons-code-manager/issues/6, fixes https://github.com/mozilla/addons-code-manager/issues/55
Here are some notes:
* There is some code in here that I used for testing (the toggle button) but I didn't write actual tests for it. I guess that will mess up our coverage. I'm not sure yet if it's worth adding tests just for that.
* The example code will be good for reference (mostly to figure out typing) but I thought we'd delete it once we replace it with something real.
* Try to play around with making mistakes, like incorrect `mapStateToProps` return values or reducer errors. TypeScript figures everything out without needing too many hints! This is pretty cool. **If you can figure out a way to break type safety, let me know.**
* I mostly used …
> Set up Redux

- .travis.yml
- README.md
> Use Node 10

- .snyk
- package.json
- stories/index.js
- stories/setup/config.js
- tsconfig.json
- yarn.lock
Fixes #4 
This just does a very basic set up of Storybook. It includes one example story which I took from the guide at https://storybook.js.org/basics/guide-react/. I imagine we'll remove that story as soon as we have our first "real" story. I also imagine we will enhance our instance of Storybook with addons, etc., but until we have an actual component for which to write a story I don't think it makes sense to do much more with it.
It works, in that you can start Storybook via `yarn storybook` and it doesn't break anything else about the app.
I wasn't sure if the deps for Storybook should go in `dependencies` or `devDependencies`, but I opted for the latter.
> Set up Storybook

- src/components/DiffView/index.spec.tsx
> Add a test for a diff with multiple files

- package.json
- src/api/index.tsx
- src/index.tsx
- yarn.lock
> Add loglevel lib

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
Fixes #18
---
I reused most of the content we have on addons-frontend.
> Add contrib files

- .travis.yml
- package.json
fixes https://github.com/mozilla/addons-code-manager/issues/66
> Ensure that storybook doesn't break

- .env.common-local
- package.json
- src/index.tsx
- yarn.lock
Fixes #26
---
This is an example of what we need. Sentry project at: https: //sentry.prod.mozaws.net/operations/addons-code-manager-test/
Once we have the hosted environments, I suppose we would just have to create the Sentry projects and add the DSNs to each `.env` file.
> Configure Sentry

- src/components/LoginButton/index.spec.tsx
- src/components/LoginButton/index.tsx
> Add test file for the LoginButton component

- src/packageJson.spec.tsx
> Fix packageJson test when a dep has a dot in its name

- .env.common-local
> Disable Sentry for local env

- src/api/index.spec.tsx
- src/api/index.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
> Implement API and reducer code for the browse API

- src/components/FileTree/index.spec.tsx
- src/components/FileTree/index.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
~~⚠️ depends on #160~~
Fixes #161
---
Before:
After:
> Sort files in FileTree

- src/server/index.spec.tsx
Fixes #133 
---
If that works for everyone, we could add some more test cases for the API proxy.
> Add more tests for the server

- src/api/index.spec.tsx
- src/api/index.tsx
- src/components/App/index.tsx
- src/pages/Browse/index.spec.tsx
- src/pages/Browse/index.tsx
- src/pages/Index/index.tsx
> Update code to reflect the latest API changes

- .gitignore
- .travis.yml
- package.json
- yarn.lock
> Add config to publish our storybook to gh-pages

- src/server/index.spec.tsx
> Add tests for the insecure proxy

- package.json
- src/jest-reporters/utils.spec.js
> Add tests for the jest-reporters/utils file

- src/configureApplication.spec.tsx
- src/configureApplication.tsx
- src/index.tsx
- stories/setup/config.ts
> Extract app setup in a function

- stories/FileTreeNode.stories.tsx
> Add story for FileNodeTree

- src/pages/Index/index.tsx
> Use Bootstrap's Col instead of div in Index component

- .eslintrc
- src/configureApplication.tsx
> Configure `@typescript-eslint/no-explicit-any` ESLint rule to throw an error

- src/components/LoginButton/index.spec.tsx
- src/components/LoginButton/index.tsx
Fixes #249
---
Small code quality issue.
>  Use REACT_APP_DEFAULT_API_VERSION in `LoginButton` component

- src/components/FileTree/index.spec.tsx
- src/components/FileTree/index.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
> Add support for mime_category field

- .eslintrc
- src/components/FileTree/index.spec.tsx
- src/components/FileTree/index.tsx
- src/components/FileTreeNode/index.spec.tsx
- src/components/FileTreeNode/index.tsx
- src/pages/Browse/index.spec.tsx
- src/pages/Browse/index.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- stories/FileTreeNode.stories.tsx
~~⚠️ depends on #243~~
We will probably iterate over it but this PR fixes #108.
---
> Select a file and fetch its content

- src/api/index.spec.tsx
- src/api/index.tsx
- src/components/App/index.spec.tsx
- src/components/App/index.tsx
- src/components/App/styles.module.scss
- src/components/Navbar/index.spec.tsx
- src/components/Navbar/index.tsx
- src/reducers/users.spec.tsx
- src/reducers/users.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/239
Here are the new UI states:
<details>
<summary>screencast</summary>
</details>
> Make user loading state more robust

- src/pages/Compare/index.spec.tsx
For some reasons, I missed this test case when applying request changes 😢
> Add better version IDs in the last Compare test case

- .eslintrc
- package.json
- yarn.lock
> Add eslint-config-prettier

- src/pages/Browse/index.spec.tsx
- src/pages/Compare/index.spec.tsx
> Add assertions for thunk props

- stories/FileTree.stories.tsx
> Add FileTree story

- src/components/Navbar/index.spec.tsx
- src/components/Navbar/index.tsx
- src/components/Navbar/styles.module.scss
> Use `Link` component in Navbar title

- stories/Navbar.stories.tsx
- stories/utils.tsx
Fixes #271 
⚠️ depends on #270 
---
> Navbar story

- src/@types/react-diff-view/index.d.ts
- src/components/CodeView/index.spec.tsx
- src/components/CodeView/index.tsx
- src/components/CodeView/utils.spec.tsx
- src/components/CodeView/utils.tsx
- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
- src/components/DiffView/styles.module.scss
- src/pages/Compare/index.tsx
- src/scss/variables.scss
- src/utils.spec.tsx
- src/utils.tsx
- stories/DiffView.stories.tsx
Fixes #282 
~~⚠️ depends on #285 and #291~~
---
> Syntax HL in diff view

- src/server/index.spec.tsx
- src/server/index.tsx
> Whitelist  the addons-linter validation report URL

- package.json
- src/components/LinterMessage/index.spec.tsx
- src/components/LinterMessage/index.tsx
- src/components/LinterMessage/styles.module.scss
- src/reducers/linter.tsx
- stories/LinterMessage.stories.tsx
- yarn.lock
Fixes https://github.com/mozilla/addons-code-manager/issues/295
Here is a sampling of the variants:
> Adds a LinterMessage component

- .travis.yml
> Use Node 11.10

- package.json
- src/packageJson.spec.tsx
- yarn.lock
> Fix babel-preset-react-app version (temporarily)

- src/pages/Browse/index.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
Fixes #248 
This one is a bit smaller than the previous patch 😉
> Return mimeType and type from getVersionFile

- src/api/index.spec.tsx
- src/api/index.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
Fixes #358
---
This patch adds some code to call the Compare API (not released yet) and some types.
> Add API code and types for the compare API

- src/configureStore.spec.tsx
- src/configureStore.tsx
- src/reducers/linter.spec.tsx
- src/reducers/linter.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/370
I have another patch that applies this to the UI so I think it's a good structure to start with.
> Add reducer / thunk for fetching and storing linter messages

- src/components/FileMetadata/index.spec.tsx
- src/components/FileMetadata/index.tsx
- src/test-helpers.tsx
- stories/FileMetadata.stories.tsx
Fixes #345 
Note: some follow-ups are needed, which I fill file and link back to the original issue.
> Create FileMetadata component

- src/components/ImageView/index.spec.tsx
- src/reducers/linter.spec.tsx
- src/reducers/users.spec.tsx
- src/reducers/versions.spec.tsx
- src/test-helpers.tsx
> Rename getFakeLogger to createFakeLogger

- .circleci/config.yml
This should fix the Circle-CI build.
> Make sure directory exists before saving image

- src/components/FileMetadata/index.tsx
- src/components/FileMetadata/styles.module.scss
- src/pages/Browse/index.spec.tsx
- src/pages/Browse/index.tsx
- src/pages/Browse/styles.module.scss
> Add FileMetadata in browse page

- src/components/FileTree/index.spec.tsx
- src/components/FileTree/index.tsx
- src/components/FileTreeNode/index.spec.tsx
- src/components/FileTreeNode/index.tsx
- src/components/FileTreeNode/styles.module.scss
- stories/FileTree.stories.tsx
- stories/FileTreeNode.stories.tsx
> Mark a file node as selected

- src/components/LinterProvider/index.spec.tsx
- src/components/LinterProvider/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/414
I tested it by applying it to `DiffView` and it's working. I think it should work for the other components as well. To keep this easier to review, I will do the actual refactoring in https://github.com/mozilla/addons-code-manager/issues/438
> Add LinterProvider to provide linter messages

- src/components/LinterMessage/index.spec.tsx
- src/components/LinterMessage/index.tsx
- stories/LinterMessage.stories.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/383
Example:
> Handle MDN links correctly

- src/server/index.spec.tsx
- src/server/index.tsx
> Relax CSP `script-src` for local dev

- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
- src/components/LinterProvider/index.tsx
- src/test-helpers.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/441
The next patches are going to be a bit big so maybe it's easier if I break them up.
> Apply LinterProvider to DiffView

- scripts/server.tsx
- src/server/index.spec.tsx
- src/server/index.tsx
> Support SERVER_HOST

- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
> Add a toggleExpandedPath action

- src/components/FileMetadata/styles.module.scss
- stories/FileMetadata.stories.tsx
> Fix overflow issue in `FileMetadata` component

- src/server/index.spec.tsx
- src/server/index.tsx
> Add Sentry to CSP when enabled

- src/components/FileTree/index.spec.tsx
- src/components/FileTree/index.tsx
- src/components/FileTree/styles.module.scss
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
~~Depends on #503~~ 
Fixes #469
> Allow the FileTree to expand and collapse

- src/components/FileTree/index.spec.tsx
- src/pages/Browse/index.tsx
- src/pages/Compare/index.spec.tsx
- src/pages/Compare/index.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
> Change the signature of `getVersionInfo()`

- src/components/FileTreeNode/index.spec.tsx
- src/components/FileTreeNode/index.tsx
- src/reducers/linter.spec.tsx
- src/reducers/linter.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/548
My plan is to use this new function here: https://github.com/mozilla/addons-code-manager/pull/542/files#diff-4a3375c826127680658868411c3f42d3R158
> Extract findMostSevereType() for linter messages

- src/components/App/index.spec.tsx
- src/components/App/index.tsx
> Do not dispatch setAuthToken when token exists in state

- src/components/FileTree/index.spec.tsx
- src/components/FileTree/index.tsx
Fixes #563 
---
I removed the test case because I could not find an easy way to fix it... 🙈
> Fix log call in FileTree

- src/pages/Browse/index.spec.tsx
- src/pages/Browse/index.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
> Avoid infinite loop when file could not be fetched in Browse component

- package.json
- src/configureStore.spec.tsx
- src/configureStore.tsx
- src/index.tsx
- src/reducers/index.tsx
- yarn.lock
Fixes #48 
---
This patch only adds `connected-react-router`.
> Add Connected React Router

- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
Fixes #562 
~~Depends on #468~~
Note that only the final commit in this PR is relevant. Hat tip to @willdurand for the super-simple solution. 🎩
>  Open the parent folder(s) when navigating to a new file 

- src/components/LinterProvider/index.spec.tsx
- src/components/LinterProvider/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/559
> Always re-render LinterProvider on location change

- src/reducers/fileTree.spec.tsx
- src/reducers/fileTree.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
> Open parent folders for the default file

- src/components/LinterProvider/index.spec.tsx
- src/components/LinterProvider/index.tsx
- src/reducers/linter.spec.tsx
- src/reducers/linter.tsx
> Fetch linter messages

- .env.common-local
- src/pages/Index/index.spec.tsx
- src/pages/Index/index.tsx
> Update index page with some links

- src/components/Skeleton/index.spec.tsx
- src/components/Skeleton/index.tsx
- src/components/Skeleton/styles.module.scss
- src/components/VersionSelect/index.tsx
- src/components/VersionSelect/styles.module.scss
- stories/Skeleton.stories.tsx
See: https://github.com/mozilla/addons-code-manager/pull/606#pullrequestreview-227866846
---
Before:
After:
> CSS fixes for Skeleton/VersionSelect

- .eslintrc
- package.json
- src/@types/storybook-addon-root-attribute/index.d.ts
- src/components/FullscreenGrid/index.spec.tsx
- src/components/FullscreenGrid/index.tsx
- src/components/FullscreenGrid/styles.module.scss
- stories/FullscreenGrid.stories.tsx
- stories/setup/addons.tsx
- stories/setup/config.tsx
- stories/setup/styles.scss
- stories/utils.tsx
- yarn.lock
Fixes https://github.com/mozilla/addons-code-manager/issues/634
This may need tweaks once I try to fit the layout into it but I'm pretty sure it will work! 🔥 
Storybook samples:
> Add a FullscreenGrid component

- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
> Add status information to VersionEntry

- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
> Retain expandedPaths when loading version info

- src/reducers/fileTree.spec.tsx
- src/reducers/fileTree.tsx
> getRelativeMessageUid should also return a path

- src/reducers/fileTree.spec.tsx
- src/reducers/fileTree.tsx
> Create a function to return the next/previous path with a diff

- package.json
- src/components/AccordionMenu/index.spec.tsx
- src/components/AccordionMenu/index.tsx
- src/components/AccordionMenu/styles.module.scss
- src/components/FullscreenGrid/index.tsx
- src/configureApplication.tsx
- src/typeUtils.tsx
- stories/AccordionMenu.stories.tsx
- stories/FullscreenGrid.stories.tsx
- stories/setup/styles.scss
- stories/utils.tsx
- yarn.lock
Fixes https://github.com/mozilla/addons-code-manager/issues/667
~~⚠️ depends on https://github.com/mozilla/addons-code-manager/issues/668~~
<details>
</details>
> Add an AccordionMenu component

- src/components/CodeOverview/index.spec.tsx
- src/components/FileTreeNode/index.spec.tsx
- src/components/FileTreeNode/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/680
~~🌵 Depends on https://github.com/mozilla/addons-code-manager/pull/681~~
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Scroll a FileTreeNode into view when needed

- .env
> Update .env to reference v5 API rather than v4

- .travis.yml
- src/api/index.tsx
Fixes #698 
---
I wasnt sure but it works as I want.. First commit is the patch, second commit shows that it works in case of a TS error, third commit makes it green again.
> Add a new job for `yarn serve` on travis-ci

- src/reducers/fileTree.spec.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
> Create a getRelativeDiff function to return an anchor or path for the next/previous diff

- src/reducers/fullscreenGrid.spec.tsx
- src/reducers/fullscreenGrid.tsx
- src/reducers/index.tsx
Fixes #731 
---
Extracted from #721
> Add fullscreenGrid reducer

- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
- src/pages/Compare/index.spec.tsx
- src/pages/Compare/index.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- stories/DiffView.stories.tsx
> Change the versions reducer to work with a single diff per file rather than an array

- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
Fixes #726 
Note that this should land at the same time as https://github.com/mozilla/addons-server/pull/11402.
> Update code to deal with API returning a single diff object

- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
> Select and scroll to the first/last diff on the compare page

- .env
- .env.common-local
- .env.dev
- .env.stage
- src/pages/Index/index.spec.tsx
- src/pages/Index/index.tsx
- src/pages/Index/styles.module.scss
- src/server/index.spec.tsx
- src/server/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/762 with some simple buttons.
> Allow error simulation to test Sentry

- src/components/KeyboardShortcuts/index.spec.tsx
- src/components/KeyboardShortcuts/index.tsx
- src/components/KeyboardShortcuts/styles.module.scss
- src/components/VersionFileViewer/index.spec.tsx
- src/components/VersionFileViewer/index.tsx
- src/pages/Compare/index.spec.tsx
- src/pages/Compare/index.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
Fixes #615 
~~Depends on #722~~ 
There are a couple of tests that are not really how I'd like them, but I figured the best way to get feedback was to submit the code for review and see what suggestions come back.
> Provide keyboard navigation for next / previous diff

- .env.dev
- .env.stage
- README.md
Fixes https://github.com/mozilla/addons-code-manager/issues/792
> Document some configuration gotchas

- src/components/KeyboardShortcuts/index.spec.tsx
- src/components/KeyboardShortcuts/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/770
> Support keys + 'Search for text when you start typing' pref

- src/reducers/fileTree.spec.tsx
- src/reducers/fileTree.tsx
> Return a line from getRelativeMessage

- src/components/CodeOverview/index.spec.tsx
- src/components/CodeOverview/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/682
> Always scroll to a linter message when clicked

- src/refractor/index.tsx
- src/refractor/prism.overrides.scss
> higher contrast ratio for text files

- src/reducers/fileTree.spec.tsx
- src/reducers/fileTree.tsx
- src/utils.tsx
> Implement goToRelativeMessage

- src/components/CodeOverview/styles.module.scss
- src/components/FullscreenGrid/ContentShell.spec.tsx
- src/components/FullscreenGrid/ContentShell.tsx
- src/components/FullscreenGrid/index.spec.tsx
- src/components/FullscreenGrid/index.tsx
- src/components/FullscreenGrid/styles.module.scss
- src/components/SidePanel/index.spec.tsx
- src/components/SidePanel/index.tsx
- src/components/SidePanel/styles.module.scss
- src/components/VersionFileViewer/index.tsx
- src/components/VersionFileViewer/styles.module.scss
Fixes #742
---
Maybe we could try to de-duplicate the code for the two panels in `ContentShell`, but maybe not...
> Toggle alt side panel

- stories/FullscreenGrid.stories.tsx
- stories/setup/styles.scss
Fixes https://github.com/mozilla/addons-code-manager/issues/827
Before:
After:
> Fix the FullscreenGrid story

- src/components/CodeView/index.spec.tsx
- src/components/CodeView/index.tsx
- src/components/CodeView/utils.spec.tsx
- src/components/CodeView/utils.tsx
- src/components/KeyboardShortcuts/index.spec.tsx
- src/components/KeyboardShortcuts/index.tsx
- src/components/VersionFileViewer/index.spec.tsx
- src/components/VersionFileViewer/index.tsx
>  Enable keyboard navigation between linter messages 

- src/components/CodeOverview/index.spec.tsx
- src/components/CodeOverview/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/830
> Render code overview after toggling alt side panel

- src/reducers/fileTree.spec.tsx
- src/reducers/fileTree.tsx
> Allow for navigating linter messages from a file without any messages

- src/components/AccordionMenu/index.spec.tsx
- src/components/AccordionMenu/index.tsx
- src/components/AccordionMenu/styles.module.scss
- src/components/Button/index.spec.tsx
- src/components/Button/index.tsx
- src/components/Button/styles.module.scss
- src/components/ToggleButton/index.spec.tsx
- src/components/ToggleButton/index.tsx
- src/components/ToggleButton/styles.module.scss
Fixes #737 
It would be nice to use this Button component in [FileTree](https://github.com/mozilla/addons-code-manager/blob/83773190ae79e6186656b0ac2bcfb937faa5bc02/src/components/FileTree/index.tsx#L147) as well.
> Create a Button component

- src/components/FileMetadata/index.spec.tsx
- src/pages/Compare/index.spec.tsx
- src/reducers/versions.spec.tsx
- src/test-helpers.tsx
- stories/FileMetadata.stories.tsx
- stories/FileTree.stories.tsx
> Use createStoreWithVersion helper

- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
> Add a target for global messages to DiffView

- src/components/CodeOverview/index.spec.tsx
- src/components/CodeView/index.spec.tsx
- src/components/FileTreeNode/index.spec.tsx
- src/components/FileTreeNode/index.tsx
- src/components/LinterProvider/index.spec.tsx
- src/components/LinterProvider/index.tsx
- src/reducers/fileTree.spec.tsx
- src/reducers/fileTree.tsx
- src/reducers/linter.spec.tsx
- src/reducers/linter.tsx
- src/test-helpers.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/879
> Store linter messages that apply to entire add-on

- src/reducers/versions.tsx
> Keep old version data in toggleExpandedPaths action

- src/components/CodeOverview/styles.module.scss
- src/components/FullscreenGrid/ContentShell.spec.tsx
- src/components/FullscreenGrid/ContentShell.tsx
- src/components/FullscreenGrid/styles.module.scss
- src/components/SidePanel/index.spec.tsx
- src/components/SidePanel/index.tsx
- src/components/SidePanel/styles.module.scss
- src/components/VersionFileViewer/index.tsx
- src/components/VersionFileViewer/styles.module.scss
- stories/AccordionMenu.stories.tsx
- stories/setup/styles.scss
Fixes #873 
@kumar303 
Great. Your solution is much better. I created this PR without any changes from you [patch](https://github.com/mozilla/addons-code-manager/issues/873#issuecomment-507317163).
> Fix UI inconsistency in the right side panel #873

- README.md
Fixes https://github.com/mozilla/addons-code-manager/issues/929
> Document tips on profiling performance

- src/components/Button/styles.module.scss
- src/components/FileMetadata/styles.module.scss
- src/components/FileTree/styles.module.scss
- src/components/FullscreenGrid/styles.module.scss
- src/components/ImageView/styles.module.scss
- src/components/KeyboardShortcuts/styles.module.scss
- src/components/SidePanel/styles.module.scss
- src/pages/Compare/styles.module.scss
- src/scss/mixins.scss
- stories/setup/styles.scss
> Converts common border styles to a Sass mixin

- src/reducers/fileTree.tsx
- src/reducers/versions.tsx
- src/utils.spec.tsx
- src/utils.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/949
This will be used as the *Show original diff* link in https://github.com/mozilla/addons-code-manager/pull/951 which will reload the page with a new query param.
> Function for adding params to a query string

- src/pages/Index/index.spec.tsx
- src/pages/Index/index.tsx
> Title updating when navigating to homepage 

- src/components/FileMetadata/index.spec.tsx
- src/components/FileTreeNode/index.spec.tsx
- src/components/KeyboardShortcuts/index.spec.tsx
- src/components/Navbar/index.spec.tsx
- src/pages/Compare/index.spec.tsx
- src/reducers/versions.spec.tsx
- src/test-helpers.tsx
- stories/FileMetadata.stories.tsx
- stories/FileTree.stories.tsx
- stories/FileTreeNode.stories.tsx
Fixes #965 
Hey @kumar303 , I had to make some changes in the `createStoreWithVersion()` in order to use object parameters,
Please let me know if I approached it right or if any changes are required.
Thanks!
> Converted parameters to single object in createStoreWithVersion()

- src/components/FileTreeNode/index.tsx
- src/components/FileTreeNode/styles.module.scss
> Fix folder name label position

- package.json
- yarn.lock
This supersedes https://github.com/mozilla/addons-code-manager/pull/1012
> Upgrade react-diff-view from 2.1.4 to 2.2.0

- src/components/Comment/index.spec.tsx
- src/components/Comment/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1030
> Don't propagate keydown from Comment textarea

- src/api/index.spec.tsx
- src/api/index.tsx
- src/components/Comment/index.tsx
- src/reducers/comments.spec.tsx
- src/reducers/comments.tsx
- src/test-helpers.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1039
> Add API for creating / updating a comment

- src/components/Commentable/index.spec.tsx
- src/components/Commentable/index.tsx
- stories/Commentable.stories.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1059
> Add features to Commentable needed by CodeView

- README.md
I forgot how our special local configuration works so we should document this 🤦‍♂
> Actually document local configuration

- src/components/FileTree/index.spec.tsx
- src/components/FileTree/index.tsx
- src/components/FileTreeNode/index.spec.tsx
- src/components/FileTreeNode/index.tsx
- src/components/KeyboardShortcuts/index.spec.tsx
- src/components/KeyboardShortcuts/index.tsx
- src/components/VersionChooser/index.spec.tsx
- src/components/VersionChooser/index.tsx
- src/components/VersionFileViewer/index.spec.tsx
- src/components/VersionFileViewer/index.tsx
- src/pages/Browse/index.spec.tsx
- src/pages/Browse/index.tsx
- src/pages/Compare/index.spec.tsx
- src/pages/Compare/index.tsx
- src/reducers/fileTree.spec.tsx
- src/reducers/fileTree.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
- stories/FileTree.stories.tsx
- stories/FileTreeNode.stories.tsx
Fixes #820
Fixes https://github.com/mozilla/addons-code-manager/issues/777
@kumar303  Would you please take a look at this patch when you have time (mainly `reducers/versions.tsx`)? It still needs a lot of work, but I wish to make sure I was on track.
> Add new state key versionEntries

- src/api/index.tsx
- src/components/CodeOverview/index.tsx
- src/components/FileTree/index.tsx
- src/components/GlobalLinterMessages/index.tsx
- src/components/KeyboardShortcuts/index.tsx
- src/components/LinterProvider/index.tsx
- src/components/VersionFileViewer/index.tsx
- src/jest-matchers/index.tsx
- src/pages/Browse/index.tsx
- src/pages/Compare/index.tsx
- src/reducers/comments.tsx
- src/reducers/fileTree.tsx
- src/reducers/linter.tsx
- src/reducers/versions.tsx
- src/utils.tsx
Fixes #1043 
Sorry, I accidentally closed the old one #1056.
> Fix all uses of void

- src/api/index.spec.tsx
- src/api/index.tsx
- src/reducers/comments.spec.tsx
- src/reducers/comments.tsx
- src/test-helpers.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1091
> Add API and thunk for fetching comments

- src/reducers/comments.spec.tsx
- src/reducers/comments.tsx
- src/test-helpers.tsx
- stories/CommentList.stories.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1096
> Make setComments() easier in fetchAndLoadComments

- src/pages/Browse/index.spec.tsx
- src/pages/Browse/index.tsx
> Preload next file in browse mode

- src/reducers/comments.spec.tsx
- src/reducers/comments.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1121
> Add thunk / reducer for deleting a comment

- src/components/CodeOverview/index.spec.tsx
- src/components/Comment/index.spec.tsx
- src/components/Comment/index.tsx
- src/components/Comment/styles.module.scss
- src/components/FileTree/index.spec.tsx
- src/components/KeyboardShortcuts/index.spec.tsx
- src/pages/Index/index.spec.tsx
- src/test-helpers.tsx
- stories/Comment.stories.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/714
<details>
</details>
> Delete a comment on a specific line

- src/pages/Compare/index.spec.tsx
- src/pages/Compare/index.tsx
- src/test-helpers.tsx
> Preload next diff in compare mode

- src/reducers/comments.spec.tsx
- src/reducers/comments.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1144
> Adjust comments reducer for finalizing a review

- src/components/CommentSummaryButton/index.spec.tsx
- src/components/CommentSummaryButton/index.tsx
- src/reducers/comments.spec.tsx
- src/reducers/comments.tsx
- stories/CommentSummaryButton.stories.tsx
~~⚠️  Depends on https://github.com/mozilla/addons-code-manager/pull/1165~~
Fixes https://github.com/mozilla/addons-code-manager/issues/1166
> Rename summary overlay 1166

- src/components/CodeView/index.spec.tsx
- src/components/CodeView/index.tsx
> Scroll global linter message into view

- src/reducers/comments.spec.tsx
- src/reducers/comments.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1175
> Add selector to know if a file path has comments

- src/components/FileTreeNode/index.spec.tsx
- src/components/FileTreeNode/index.tsx
- src/components/FileTreeNode/styles.module.scss
- stories/FileTree.stories.tsx
- stories/setup/styles.scss
~~⚠️  Depends on https://github.com/mozilla/addons-code-manager/pull/1176~~
Fixes https://github.com/mozilla/addons-code-manager/issues/1174
<details>
<summary>Screenshots</summary>
</details>
> Indicate when a file or folder has comments

- .env
- .env.dev
Fixes https://github.com/mozilla/addons-code-manager/issues/1202
> Enable commenting in prod

- .gitignore
- .vscode/settings.json
- README.md
Fixes https://github.com/mozilla/addons-code-manager/issues/1209
> Use the correct TypeScript version in VSCode

- src/components/Comment/index.spec.tsx
- src/components/Comment/index.tsx
- src/reducers/comments.spec.tsx
- src/reducers/comments.tsx
> Add a button to cancel entering comment

- stories/Comment.stories.tsx
> Add comments story for confirming discard

- src/components/CommentSummaryButton/index.spec.tsx
- src/components/CommentSummaryButton/index.tsx
- src/components/CommentSummaryButton/styles.module.scss
- src/components/PopoverButton/index.spec.tsx
- src/components/PopoverButton/index.tsx
- src/components/PopoverButton/styles.module.scss
- stories/PopoverButton.stories.tsx
- stories/setup/styles.scss
Fixes https://github.com/mozilla/addons-code-manager/issues/1249
> Extract PopoverButton from comment summary

- src/components/CodeView/index.tsx
- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
- src/components/SlowPageAlert/index.spec.tsx
- src/components/SlowPageAlert/index.tsx
- src/utils.spec.tsx
- src/utils.tsx
> Don't trim diffs by default

- src/components/FullscreenGrid/ContentShell.spec.tsx
- src/components/FullscreenGrid/ContentShell.tsx
- src/components/FullscreenGrid/index.spec.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1247
> Recreate the content DOM node on location changes

- src/components/CommentSummaryButton/index.spec.tsx
- src/components/CommentSummaryButton/index.tsx
- src/components/PopoverButton/index.spec.tsx
- src/components/PopoverButton/index.tsx
- src/configureStore.tsx
- src/reducers/comments.spec.tsx
- src/reducers/comments.tsx
- src/reducers/index.tsx
- src/reducers/popover.spec.tsx
- src/reducers/popover.tsx
- stories/CommentSummaryButton.stories.tsx
- stories/PopoverButton.stories.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1256
> Move Redux control into PopoverButton

- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1266
> Do not fetch a version if a fetch is in progress

- src/components/CommentSummaryButton/index.spec.tsx
- src/components/CommentSummaryButton/index.tsx
- src/components/CommentSummaryButton/styles.module.scss
- src/components/PopoverButton/index.spec.tsx
- src/components/PopoverButton/index.tsx
- src/components/PopoverButton/styles.module.scss
- src/test-helpers.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1272
> Adjust CommentSummaryButton config

- src/components/CodeView/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1280
> Increase line limit for detecting slow files

- src/components/VersionSelect/index.spec.tsx
- src/components/VersionSelect/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1276
> Support custom form control class in VersionSelect

- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
> Allow VersionEntry.sha256 to be null

- src/components/Comment/index.spec.tsx
- src/components/Comment/index.tsx
- src/components/CommentList/index.spec.tsx
- src/components/CommentList/index.tsx
- src/components/CommentSummary/index.tsx
- src/components/Commentable/AddComment.spec.tsx
- src/components/Commentable/AddComment.tsx
- src/reducers/comments.spec.tsx
- src/reducers/comments.tsx
- src/test-helpers.tsx
- stories/Comment.stories.tsx
- stories/CommentList.stories.tsx
> Add edit button

- src/components/VersionChooser/index.spec.tsx
- src/components/VersionChooser/index.tsx
- src/test-helpers.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1305
I discovered and fixed a few other bugs in here 👀
> Preserve location query string in VersionChooser

- yarn.lock
Rebuild the lockfile to refresh the transitive deps.
> Rebuild lockfile

- src/components/CodeView/index.spec.tsx
- src/components/CodeView/index.tsx
- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
> Disable syntax highlighting whenever a file is truncated

- src/components/FileTree/index.spec.tsx
- src/components/Navbar/index.spec.tsx
- src/components/VersionFileViewer/index.spec.tsx
- src/pages/Browse/index.spec.tsx
- src/pages/Compare/index.spec.tsx
- src/reducers/fileTree.spec.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
- stories/Navbar.stories.tsx
> Do not change path info when loading a base version

- src/components/Comment/index.spec.tsx
- src/components/Comment/index.tsx
- src/components/CommentList/index.spec.tsx
- src/components/CommentList/index.tsx
- stories/Comment.stories.tsx
> Remove the readOnly prop in Comment component

- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1338
> Dispatch beginFetchVersionFile() in fetchVersion()

- src/@types/react-storybook-addon-chapters/index.d.ts
- src/components/App/index.tsx
- src/components/FileTreeNode/index.spec.tsx
- src/components/VersionChooser/index.tsx
- src/jest-matchers/index.spec.tsx
- yarn.lock
Replaces https://github.com/mozilla/addons-code-manager/pull/1196
> Lock file maintenance

- src/components/CodeView/index.tsx
- src/components/CodeView/styles.module.scss
> Wrap long lines in Browse

- src/pages/Compare/index.spec.tsx
- src/pages/Compare/index.tsx
> Update side panels in compare when navigating back and forward

- src/pages/Compare/index.spec.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
> Store sha256 in version file

- .travis.yml
See also: https://github.com/mozilla/addons-code-manager/pull/1401
---
I guess I should have requested a review instead of quick-fixing the build.. Sorry about that.
> Re add `fast_finish` to travis config

- src/pages/Compare/index.spec.tsx
- src/pages/Compare/index.tsx
> Do not fetch deleted files in Compare mode

- src/components/VersionFileViewer/index.spec.tsx
- src/components/VersionFileViewer/index.tsx
- src/pages/Compare/index.spec.tsx
- src/pages/Compare/index.tsx
Fixes #1410
After:
http://localhost:3000/en-US/compare/325576/versions/1688306...1690075/?path=META-INF%2Fmozilla.sf
> Show a message in the info panel for deleted files

- src/pages/Compare/index.spec.tsx
Fixes  #1413
I found I could use the existing helper to make the tests very concise.
> Clean up compare page tests

- package.json
> Revert react-scripts to v3.3.0

- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
> Output as much of a diff as we can when trimming

- .travis.yml
> Only notify on master branches

- src/server/index.spec.tsx
- src/server/index.tsx
- src/tracking.spec.tsx
- src/tracking.tsx
> Use transport mechanism "beacon" for Google Analytics

- src/components/App/index.spec.tsx
- src/components/App/index.tsx
Fixes #1450 
~~Depends on #1452~~
> Send fetch timings to GA

- src/components/Navbar/index.spec.tsx
- src/components/Navbar/index.tsx
- src/components/Navbar/styles.module.scss
> Provide link to old file viewer for browse view

- src/reducers/versions.tsx
- src/test-helpers.tsx
Fixes #1476 
Note that I wasn't able to test the locally because of https://github.com/mozilla/addons-server/issues/13665, which although it's been fixed, hasn't deployed to dev yet.
I suggest someone wait to test this locally before merging.
> Update PartialExternalVersion type after API changes land

- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
> Adjust reducer to store and return isMinified

- src/components/DiffView/index.spec.tsx
- src/components/Navbar/index.spec.tsx
- src/components/Navbar/index.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
> Add a link to legacy file viewer in Compare page

- src/components/CodeView/index.spec.tsx
- src/components/CodeView/index.tsx
- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
- src/pages/Browse/index.tsx
- src/pages/Compare/index.tsx
- src/reducers/versions.tsx
- src/utils.spec.tsx
- src/utils.tsx
- stories/CodeOverview.stories.tsx
- stories/CodeView.stories.tsx
- stories/DiffView.stories.tsx
- stories/FadableContent.stories.tsx
> Truncate all minified files by default

- .circleci/config.yml
Fixes https://github.com/mozilla/addons-code-manager/issues/1500
> Update circle-ci version to 2.1

- src/components/CodeView/index.spec.tsx
- src/components/CodeView/index.tsx
- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
- src/components/SlowPageAlert/index.spec.tsx
- src/components/SlowPageAlert/index.tsx
- src/test-helpers.tsx
- stories/SlowPageAlert.stories.tsx
> Use a client-side redirect when switching between allowing slow code and not

- src/components/CodeView/index.spec.tsx
- src/components/CodeView/index.tsx
- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
- src/utils.spec.tsx
- src/utils.tsx
> Send the URL along with the performance timings

- src/components/CodeView/index.spec.tsx
- src/components/CodeView/index.tsx
- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
- src/utils.spec.tsx
- src/utils.tsx
> Change logic for truncation of files

- src/components/VersionFileViewer/index.spec.tsx
- src/components/VersionFileViewer/index.tsx
- src/pages/Browse/index.spec.tsx
- src/pages/Browse/index.tsx
- src/pages/Compare/index.spec.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
> Adjust logic for the versions reducer to reflect API changes

- src/@types/react-diff-view/index.d.ts
- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
- src/test-helpers.tsx
> Do not highlight code that has been trimmed in the DiffView

- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
> Remove file properties no longer available via the APIs

- src/components/KeyboardShortcuts/index.spec.tsx
- src/components/LinterProvider/index.spec.tsx
- src/components/VersionFileViewer/index.spec.tsx
- src/pages/Browse/index.spec.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
- stories/CodeOverview.stories.tsx
- stories/CodeView.stories.tsx
- stories/DiffView.stories.tsx
> Switch from version.file.entries to version.file_entries

- src/api/index.spec.tsx
- src/api/index.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
> Only retrieve file info when that's all we need, in the Browse view

- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
> Fix logic for checking for a failed tokenize result

- src/reducers/comments.spec.tsx
- src/reducers/comments.tsx
- src/test-helpers.tsx
> Remove version info from draft_comments API

- package.json
- yarn.lock
Fixes #1609 
Based on https://community.codecov.io/t/github-public-repo-error-processing-coverage-reports/1457
> Attempt to fix codecov

- package.json
- yarn.lock
Maybe a temporary fix for #1607
> rollback textarea-autosize to v7.1.2

- src/components/FileMetadata/index.spec.tsx
- src/components/FileMetadata/index.tsx
- src/components/Navbar/index.tsx
- src/components/VersionChooser/index.spec.tsx
- src/components/VersionFileViewer/index.spec.tsx
- src/components/VersionFileViewer/index.tsx
- src/components/VersionSelect/index.spec.tsx
- src/components/VersionSelect/index.tsx
- src/pages/Browse/index.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
> Rename the `version` property to `versionString`

- src/components/VersionFileViewer/index.spec.tsx
- src/components/VersionFileViewer/index.tsx
- src/utils.spec.tsx
- src/utils.tsx
> Allow CodeOverview to render the content of diffs

- src/api/index.spec.tsx
- src/api/index.tsx
- src/reducers/linter.spec.tsx
- src/reducers/linter.tsx
- src/server/index.spec.tsx
- src/server/index.tsx
> Call validation.json endpoint as an API

- src/server/index.spec.tsx
- src/server/index.tsx
> Fix logic for analyticsPath for local dev

- src/components/DiffView/index.spec.tsx
- src/pages/Compare/index.spec.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/utils.spec.tsx
Fixes #1638 
~~Depends on #1636~~
It probably makes sense to wait for #1636 to land before reviewing this, as it will make the diff much smaller.
> Add types to support VersionDiffs

- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
> Remove code for base_file

- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
- src/test-helpers.tsx
> Add reducer support for retrieving and storing diff files

- src/components/Navbar/index.spec.tsx
- src/components/Navbar/index.tsx
- src/reducers/versions.tsx
> Make reviewer tools link work for deleted add-ons

- src/components/App/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1661
> Add a comment about routing and nginx

- Dockerfile
> Upgrade node version to v12

- .circleci/config.yml
> Login to dockerhub before pulling docker images for building

- .eslintrc
- src/components/AccordionMenu/index.spec.tsx
- src/components/AccordionMenu/index.tsx
- src/components/FileMetadata/index.spec.tsx
- src/components/FileMetadata/index.tsx
- src/components/VersionFileViewer/index.tsx
- stories/FileMetadata.stories.tsx
> Permanently show current file info panel

- src/components/VersionFileViewer/index.tsx
- stories/AccordionMenu.stories.tsx
> Update the title of the Information panel

- src/components/DiffView/index.spec.tsx
- src/components/DiffView/index.tsx
> Hide messages on deleted lines

- stories/setup/webpack.config.js
Fixes https://github.com/mozilla/addons-code-manager/issues/1823
---
We don't really need that feature anyway.
> Disable sourcemap in storybook

- src/components/Navbar/index.spec.tsx
- src/components/Navbar/index.tsx
- src/pages/Browse/index.spec.tsx
- src/pages/Browse/index.tsx
- src/pages/Compare/index.spec.tsx
- src/pages/Compare/index.tsx
- src/reducers/fileTree.spec.tsx
- src/reducers/fileTree.tsx
- src/reducers/versions.spec.tsx
- src/reducers/versions.tsx
> Handle missing add-on name

- README.md
> Issue #1903 - Fix Contributing Guidelines link

- Dockerfile
Fix #1984
Thanks for opening a Pull Request (PR), here are a few guidelines as to what we need in your PR before we review it.
> Upgrade to node v14

- src/components/Navbar/index.spec.tsx
- src/components/Navbar/index.tsx
> Always use AMO add-on ID for linking back to reviewer tools

- .env
- src/api/index.spec.tsx
- src/api/index.tsx
- src/components/App/index.spec.tsx
- src/components/App/index.tsx
- src/configureStore.spec.tsx
- src/configureStore.tsx
- src/index.tsx
- src/reducers/api.spec.tsx
- src/reducers/api.tsx
- src/server/index.tsx
fixes #2156 - only the first commit is strictly necessary, I just renamed variables for consistency
> session token api auth

- .env
- public/index.html
- src/index.tsx
- src/reducers/api.tsx
- src/server/index.spec.tsx
- src/server/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/2156
> Fix session id auth: the data attribute in the HTML needs to match

- .circleci/config.yml
- Dockerfile
- README.md
> Switch to Node 16 by default, drop 14, start testing with 18

- .circleci/config.yml
- README.md
> Disable storybook-deployer

- src/api/index.spec.tsx
- src/api/index.tsx
- src/components/Comment/index.spec.tsx
- src/components/Comment/index.tsx
- src/reducers/comments.spec.tsx
- src/reducers/comments.tsx
- src/test-helpers.tsx
> Remove code relating to canned responses
