README.md
We probably don't need to document commands that a user won't ever run directly.
=> Only document user facing commands

package.json, src/App.module.scss, src/App.test.tsx, src/App.tsx, src/setupTests.ts, yarn.lock
~~⚠️ depends on #27~~
Fixes #1
Fixes #19 
---
Here it how it works (second commit):
- rename `.scss` file to `.module.scss`
- import it as a "JS-like module"
- use it
No need to add a scope to all CSS classes (hence shorter class names). It is guaranteed that there won't be any name collision. In production build, names can be shortened to reduce the amount of HTML sent to the client.
=> Example of CSS modules

.node-dev.json, package.json, scripts/server.tsx, src/@types/react-diff-view/index.d.ts, src/@types/universal-cookie-express/index.d.ts, src/server/index.spec.tsx, src/server/index.tsx, tsconfig.json, yarn.lock
Fixes #71
---
I use `ts-node` in production, which is good enough. The only overhead seems to be on the initial startup time, then it is alright. It is simpler to use `ts-node` over anything else so that we can decouple our server code into different TS files and still be able to run the server from a unique entrypoint and without any bundler. That's the main motivation (and also the reason I mentioned `ncc` in the issue)
I use `ts-node-dev` in developement, which watches our server code and restarts it automatically on change. It does not restart the server if frontend code is changed, which is great. It also means we have full reload in dev, no matter which code is changed :tada:
The `.node-dev.json` file has been added to configure the following features in dev mode:
- clear the …
=> Implement server code in TS

src/components/App/index.spec.tsx, src/components/App/index.tsx, src/components/LoginButton/index.tsx, src/components/Navbar/index.spec.tsx, src/components/Navbar/index.tsx, src/components/Navbar/styles.module.scss, src/utils.tsx
Fixes #76 
A couple of notes:
1. As I mentioned in today's standup, I think we should remove `profile` from the component state of `App` and move it to the Redux store. As that will require some extra work, including the creation of a reducer, I think it makes sense to defer that to a follow up.
2. I wasn't sure what to do about the "logging out" message, so I just left it in the `App` component for now. I'm not sure if we need that at all, or if it was just there to demonstrate that it works.
Logged Out:
Logged In:
=> Add a Bootstrap Navbar

src/server/index.tsx
Fixes #131 
---
This is required for #130. I cannot find a way to test this part of the server code yet, because the `proxy` call depends on another service. I'll try to get back to that in #133.
=> Fix dev proxy to inject the auth token all the time

package.json, src/components/App/index.spec.tsx, src/components/App/index.tsx, src/components/App/styles.module.scss, yarn.lock
Fixes #144
---
As discussed in #134, I added a loading state until the user profile gets loaded. It is only displayed when there is an authentication token, otherwise we see the "please log in" message.
For some reasons, the catch-all route was not working as intended (404). I fixed that but the behavior is different: the "please log in" message has precedence over the 404 (which is ok I believe).
Note: I decided to add this code in `App` so that it is done once for all.
=> Add loading state

src/api/index.spec.tsx, src/api/index.tsx
Fixes #157
---
This PR adds basic support for query parameters.
=> Add support for query params in callApi

package.json, src/@types/react-treefold/index.d.ts, src/components/FileTree/index.spec.tsx, src/components/FileTree/index.tsx, src/components/FileTree/styles.module.scss, src/configureStore.spec.tsx, src/configureStore.tsx, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/pages/Index/index.tsx, yarn.lock
Supports #39 
---
This PR adds:
- `react-treefold`, a good react tree library that does not too much things at once, so we can customize everything: https://github.com/gnapse/react-treefold
- a `FileTree` component that renders any tree coming from the browse API
Known limitations:
- ~~the API types are partial~~
- API errors are not handled at all
- files are not sorted (we should have directories first, then files IMHO) => see #162 
- ~~I store the response in the component's state until we get a reducer for that (but that's not a lot of code anyway)~~
- ~~the interface (public props) of the `FileTree` will likely change, in part because the reducer will likely allow this component to be connected (or at least to receive more precise props from the `Browse` component)~~
- styling will …
=> Start playing with Treefold

package.json, src/jest-reporters/eslint-check.js, src/jest-reporters/utils.js, tsconfig.json
Fixes #140 
This is just an initial crack at getting this to work. I simply brought a couple of files over from addons-frontend, and added a new yarn command called `test-lint`, which runs the Jest tests and also the ESLint checks.
It's a bit hacky, but the only thing I could get to work, which I picked up from https://github.com/facebook/create-react-app/issues/2474#issuecomment-321837707.
The Jest reporter and utils files are still `js` files, as opposed to `tsx` files, and I guess we'll want to rewrite them as `tsx` files, as long as Jest allows that.
Just submitting this for initial thoughts and feedback.
=> Add ESLint reporter for jest

package.json
I don't think we can cover this file with tests, so let's ignore it to have a more accurate coverage report.
=> Ignore src/index.tsx from coverage

package.json, src/components/Navbar/index.spec.tsx, src/components/Navbar/index.tsx, src/configureStore.tsx, src/reducers/users.spec.tsx, src/reducers/users.tsx, src/test-helpers.spec.tsx, src/test-helpers.tsx, yarn.lock
Fixes https://github.com/mozilla/addons-code-manager/issues/12
After some consideration (see below), redux-thunk is a pretty good option. This adds redux-thunk for handling side effects.
<hr>
*Original PR description:*
As part of https://github.com/mozilla/addons-code-manager/issues/12, here's an example of using `redux-thunk` so we can assess it.
Here are some questions worth asking:
- How testable is this?
- Does it allow our application behavior to be traced through one place?
- [maybe more questions]
Known issues:
- ~~The `(dispatch as ThunkDispatch)` type hint seems like it should be unnecessary since we have types for our middleware (see https://github.com/reduxjs/redux-thunk/issues/103) but I couldn't get the error to go away without this type hint, even when doing the same module …
=> Use redux-thunk for side effects

src/api/index.spec.tsx, src/api/index.tsx, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx
Fixes #235
---
This PR renames the api function `getVersionFile` to `getVersion`
because the current name is confusing. With the recent changes in the
API, renaming the function makes even more sense because what we really
do is retrieving a "version".
I found very confusing to use `getVersionFile` and then to dispatch a
`loadVersionInfo` in one case and `loadVersionFile` in another case. By
having `getVersion`, the code seems easier to follow to me.
=> Rename api.getVersionFile to api.getVersion

src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/test-helpers.tsx
Fixes #231
---
This PR adds a new field named `selectedPath` to the `versions` reducer. It stores the `file.selected_file` value. Given that retrieving a version without a `path` returns a default file, I also decided to store it. Last, I added a `getVersionFiles()` selector because we'll need it in the near future.
In the near future, we'll likely have a `selectPath` action.
=> Add selected_file to versions reducer (as selectedPath)

src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Minor change to make all selectors similar, i.e. all `versions`
selectors have the state as first argument, the versionId as second
argument, and then other arguments.
=> Change order of arguments in getVersionFile

.env, src/api/index.spec.tsx, src/api/index.tsx, src/jest-matchers/index.spec.tsx, src/jest-matchers/index.tsx, src/jest.d.ts, src/setupTests.tsx
Fixes #192 
Note that after making this change, the data I am getting back from the API no longer contains localized strings. I believe this is because the `v4` API is currently configured to return simple strings, and not objects, in order to be backwards compatible with addons-frontend, and that there is a different endpoint we can use to get the localized strings (something like `dev4`, iirc). 
@eviljeff What is the endpoint we need to use to get localized strings back from the API, even if we pass in a `lang`, and is it currently configured to work with `addons-code-manager`?
=> Send an explicit language with API requests

.env, src/api/index.spec.tsx, src/api/index.tsx, src/components/App/index.spec.tsx, src/components/App/index.tsx, src/components/Navbar/index.spec.tsx, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/reducers/users.spec.tsx, src/reducers/users.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/test-helpers.tsx
Fixes #181 
---
This PR allows us to write code like this now: https://github.com/mozilla/addons-code-manager/pull/218/files#diff-eaeb6d1753d7786e20e90d2089ffe11e. In other words, we now have precise return types for our API calls.
The PR also adds new thunks and a bunch of test cases.
=> Add better return types for the API functions

src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/test-helpers.tsx
Fixes #180 
I'm wondering, though, what we want to do about localized strings. Making use of this new `VersionAddon` object will be the first time we have to deal with them (for the `name` property). The API returns localized strings to us, i.e., an object with a translation for different locales, but maybe that's not what we want?
I believe in addons-frontend we set up the API call so it would include a language and we'd only get the string back for the language we requested. Although we don't think we're going to support multiple languages in the app, it seems like this is probably the route we should go here. Otherwise our code is going to have to deal with these localized string objects.
What do people think?
=> Add add-on info to the `versions` reducer

src/components/FileTree/index.spec.tsx, src/components/FileTree/index.tsx, src/reducers/versions.tsx, src/utils.spec.tsx, src/utils.tsx
Fixes #261
This patch was an excuse to see how to consume localized content :)
=> Display add-on's name in the FileTree

.eslintrc, src/components/App/index.spec.tsx, src/components/App/index.tsx, src/components/DiffView/fixtures/basicDiff.tsx, src/components/DiffView/fixtures/multipleDiff.tsx, src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/components/Loading/index.spec.tsx, src/components/Loading/index.tsx, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/pages/Index/index.spec.tsx, src/pages/Index/index.tsx, stories/Loading.stories.tsx
This patch creates a new page for the "compare" (or diff) view to start this new page soon-ish (hello #111). Of course, it is incomplete as there is no API endpoint yet, but it shows the `DiffView` (and fixes a visual issue). API responses will be similar but not exactly the same so I can't find a way to DRY better than what's here.
I created a new `Loading` component to display a loading state (message for now, but could maybe be reused for other loading states).
Given that validator results will be displayed in both views, I think we need this view right now so that we can think about both use cases.
=> Introduce a Compare page

src/pages/Browse/index.spec.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/273
=> Test FileTree selectFile() through React props, not instance methods

src/components/FileTreeNode/index.tsx
Fixes #258 
---
This is a small fix for a small issue I noticed in Storybook 😎 
Before:
After:
=> Fix empty folder node height

src/@types/react-diff-view/index.d.ts, src/components/DiffView/fixtures/diffWithDeletions.tsx, src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/components/DiffView/styles.module.scss, src/pages/Compare/index.tsx, src/scss/variables.scss, stories/DiffView.stories.tsx
Fixes #281 
---
This PR improves the UI of the `DiffView` component and adds a story for it.
diff with deletions:
basic diff:
multiple diffs (which should not be supported, cf. #280):
=> Add story for DiffView and make it pretty

src/components/VersionChooser/index.spec.tsx, src/components/VersionChooser/index.tsx, src/components/VersionChooser/styles.module.scss, src/components/VersionSelect/index.spec.tsx, src/components/VersionSelect/index.tsx, src/components/VersionSelect/styles.module.scss, src/pages/Compare/index.tsx, src/test-helpers.tsx, stories/VersionChooser.stories.tsx
Fixes #293
---
This patch adds a new `VersionChooser` component (that relies on a `VersionSelect` component for DRY). It will be used to select different versions of an add-on in order to see a `diff` in the compare page.
This is only the first step. Once we get and store data from the API, we can render real data and start the work to select a version. I envision this user action as a simple click into the list of versions that updates the URL and the diff view. That's why there is no "Go" button. [GitHub does that](https://github.com/mozilla/addons-code-manager/compare), too. We will probably need an exclusion list (or at least one version) on the `VersionSelect` component too, so that we can disable the version that has been selected in the other `select` (because we can't diff the …
=> Version chooser

src/pages/NotFound/index.tsx
This is a small fix because I stumbled upon this page today and that did not look nice. I don't think it needs a review because it is about replacing a `div` with a `Col` component.
Before:
After:
=> Use bootstrap column in NotFound component

src/api/index.spec.tsx, src/api/index.tsx, src/components/VersionChooser/index.spec.tsx, src/components/VersionChooser/index.tsx, src/components/VersionSelect/index.spec.tsx, src/components/VersionSelect/index.tsx, src/pages/Compare/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/test-helpers.tsx, stories/VersionChooser.stories.tsx
Fixes #306 
~~⚠️ depends on #305~~
---
This patch adds the logic to fetch, store and give the data to the `VersionChooser` component (cf. #305). We can select versions but it does nothing yet (see #321). The Storybook has been updated to show the two main states of the `VersionChooser` component.
=> Fetch, store and render a list of versions for an add-on

src/components/CodeView/index.spec.tsx, src/components/CodeView/index.tsx, src/components/CodeView/styles.module.scss, src/scss/variables.scss, src/test-helpers.tsx, stories/CodeView.stories.tsx
Fixes #317
---
This PR adds links on each line number of the `CodeView` component so that we can link to a specific line. This is needed for the outline (#200).
=> Add anchors/links on each line of the `CodeView` component

src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes #347 
Note that this does not implement the download link. I opened #348 as a follow-up.
=> Return data required by the file footer from getVersionFile

src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx
This will be useful to make sure both #111 and #314 behave correctly. All the other components in `Compare` won't have to deal with the problem of knowing which version is the "old" one and which version is the "new" one. This check happens before any reviewer API calls.
It works because version IDs are integers and newer version IDs get higher numbers (there is some sort of auto-increment). I know we should avoid relying on the auto-increment property of an ID in general, but this is a very simple solution that works well for our purpose. I don't think we'll change the type of version IDs anytime soon (we'll likely always deal with integers) and I don't think we'll change the behavior that currently guarantees that new version IDs have higher numbers than older version IDs. Hence the …
=> Add a quick check to ensure old version is older than the new version

src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/376
=> Show global linter messages in file viewer

src/reducers/linter.spec.tsx
This is a follow-up to https://github.com/mozilla/addons-code-manager/pull/371 which fixed https://github.com/mozilla/addons-code-manager/issues/370
=> Fix test logic for the linter reducer

src/@types/refractor/index.d.ts, src/components/CodeView/utils.spec.tsx, src/components/CodeView/utils.tsx
Fixes #299
---
This patch adds test cases for the `map*` functions, used in the `CodeView` component.
=> Add tests for the map* functions

src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/pages/Compare/index.tsx, stories/DiffView.stories.tsx
Supports #111 
---
This patch has been extracted from #374 to reduce the size of the patch. The `DiffView` component should take a list of `DiffInfo` instead of a raw git diff. That's what this PR does. Everything else remains the same.
=> Pass DiffInfo[] to DiffView

src/@types/react-diff-view/index.d.ts, src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/test-helpers.tsx
Fixes #359 
~~⚠️ Depends on #356~~
---
This patch adds a function to map the diff part of the Compare API response to the internal representation needed for `react-diff-view`. It needs #356 which adds types.
Only the second commit is relevant here.
=> Add `createInternalDiffs` function to `versions` reducer

src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/components/DiffView/styles.module.scss, stories/DiffView.stories.tsx
Supports #111 
~~⚠️ depends on #375~~
---
The API returns an empty list of differences sometimes. We should support this case in `DiffView`. This patch has been extracted from #374. There is an empty header for now so that it is similar to when there are differences. In the future, we might want to add the filename (path) to this header, in both cases.
In context:
=> Support empty list of diffs in `DiffView`

src/components/CodeView/index.spec.tsx, src/components/CodeView/index.tsx, src/components/CodeView/styles.module.scss, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/reducers/linter.spec.tsx, src/reducers/linter.tsx, src/test-helpers.tsx, stories/CodeView.stories.tsx
This is the last puzzle piece to fix https://github.com/mozilla/addons-code-manager/issues/41
The UX isn't great. It accomplishes the bare minimum of showing an inline linter message. I have some ideas to make it better but I'll defer those to follow-ups.
Examples:
<hr>
<hr>
=> Show inline linter messages in code files

src/components/FileMetadata/index.spec.tsx, src/pages/Browse/index.spec.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/test-helpers.tsx, stories/FileMetadata.stories.tsx
Fixes #360
~~⚠️ depends on #361 and #375~~
---
This PR adds the logic to fetch and store a compare data (`diffs` and `mimeType`, which are both required in `DiffView`). ~~Only the last commit is relevant here.~~
I tried to bring the begin/abort actions we want to use in the near future. I have a patch for the UI in #385, which uses this patch and updates the UI for 3 cases: when an error has occurred, when fetching/loading data and when everything went well.
There is a change that impact the rest of the app: `loadVersionInfo()` does not load a "version file" implicitly. `loadVersionFile` must be called. This is needed to be able to reuse `loadVersionInfo` with a version with content (for the browse page) *or* with diff (for the compare page).
I store data for at most one file (similar to …
=> Fetch and store diffs

src/reducers/versions.spec.tsx, src/reducers/versions.tsx
This is a fix for https://github.com/mozilla/addons-server/issues/10932 so that we can have correct data in the frontend (until the API gets fixed).
The diff is on the `version` of the `manifest.json`.
Before:
After:
=> Fix changes content

src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/pages/Index/index.tsx
Fixes #292 
Fixes #362 
~~⚠️ depends on #374~~
---
This patch adds the logic for rendering diffs between two versions of an add-on. It handles errors and loading state.
=> Render diffs in Compare page

src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/reducers/linter.tsx, stories/DiffView.stories.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/409
**NOTE**: There is some duplication here between how `pages/Browse` and `components/CodeView` handle [linter messages](https://github.com/mozilla/addons-code-manager/blob/ed2f053714c09230b55ff10eb93de98d9240b1e5/src/pages/Browse/index.tsx#L82-L89). To keep this patch small-ish, I'm going to address that in a follow-up issue (https://github.com/mozilla/addons-code-manager/issues/414). The `Browse` component was doing it in an awkward way so the fixup will be slightly more involved.
=> Show global linter messages in compare view

src/@types/react-diff-view/index.d.ts, src/components/CodeView/styles.module.scss, src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/components/DiffView/styles.module.scss, stories/DiffView.stories.tsx
This implements inline linter messages which is the final part to fix https://github.com/mozilla/addons-code-manager/issues/314
In http://localhost:3000/en-US/compare/494431/versions/1532144...1532144/ you can click on `common.js` to see an inline message.
Example from storybook:
=> Show inline linter messages in the compare view

src/components/FileTree/index.spec.tsx, src/components/FileTree/index.tsx, src/components/FileTreeNode/index.spec.tsx, src/components/FileTreeNode/index.tsx, src/components/FileTreeNode/styles.module.scss, src/pages/Browse/index.tsx, src/pages/Compare/index.tsx, stories/FileTree.stories.tsx, stories/FileTreeNode.stories.tsx
Fixes #329 
Fixes #330 
~~⚠️ depends on #400~~
---
This patch adds icons/colors to indicate when a file has linter messages. Directories containing such files are also marked with icons/colors.
Additional notes:
- only the most severe linter message type is shown
- HTML titles are used to give more information about the icons
- the "error" type is usually not used because errors block the submission of a version (admins can override this behavior, though)
- the first two screenshots show a yellow color for the warnings but it has been change to orange to be more readable
- I imagine that #115 could also be implemented with an icon (and some more style probably) **UPDATE:** see https://github.com/mozilla/addons-code-manager/pull/418/commits/04cac0a2ab0f23e38540787f7cdfc44a87a82a18
With …
=> Add icons related to linter messages in FileTreeNode

src/components/FileMetadata/index.spec.tsx, src/components/FileMetadata/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/test-helpers.tsx
Fixes #353
Fixes #348 
---
This is not working because the API returns a link that requires authentication, but the UI is there. I believe the API will be fixed to return a link that works. If not, we could add some server code to fix the links in this project, but that can be done in a follow-up.
=> Expose download URL

src/components/LoginButton/index.spec.tsx, src/components/LoginButton/index.tsx, stories/LoginButton.stories.tsx
Fixes #354
---
This patch passes the current relative URL to FxA so that the user is
redirected to the right page after login.
=> Continue to the initial URL after login

src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/test-helpers.tsx
Fixes #419
---
Now that the API has been fixed, this hack is not useful anymore.
=> Remove `\n` hack on `changes[].content` in `versions` reducer

src/components/FileTree/index.spec.tsx, src/components/FileTree/index.tsx, src/components/FileTreeNode/index.spec.tsx, src/components/FileTreeNode/index.tsx, src/pages/Browse/index.tsx, src/pages/Compare/index.tsx, stories/FileTree.stories.tsx, stories/FileTreeNode.stories.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/451
This change was needed to make linter icons show up in the compare view
=> Adds LinterProvider to FileTreeNode and fixes the compare view

src/components/FileTreeNode/index.spec.tsx, src/components/FileTreeNode/index.tsx, src/components/FileTreeNode/styles.module.scss, src/pages/Index/index.tsx, src/reducers/linter.spec.tsx, src/reducers/linter.tsx, src/test-helpers.tsx
Fixes #115
~~:warning: depends on #401~~
---
This patch adds style/visual indication for file that are known (js) libraries.
You can also try this addon/version: http://localhost:3000/en-US/browse/502914/versions/1541734/
=> Add icon/title for known JS files

src/api/index.spec.tsx, src/api/index.tsx, src/components/LoginButton/index.spec.tsx, src/components/LoginButton/index.tsx
Fixes #460
Fixes #462 
---
How I tested it:
1. I tried to run the project like in prod:
```
rm -f .env.local && yarn build && yarn start
```
This should start the project at http://localhost:3000/ and the API call to fetch the user profile should have `addons.mozilla.org` as domain in the devtools > network panel (result should be a 401).
2. I ran `yarn dev` to make sure it behaves as before.
**Note:** I believe this won't fix the login issue entirely because we need some FxA changes (see: #463).
=> Add API host when not using the insecure proxy

src/components/CodeView/index.spec.tsx, src/components/CodeView/index.tsx, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/test-helpers.tsx, stories/CodeView.stories.tsx, stories/DiffView.stories.tsx, stories/utils.tsx
This is the final patch to fix https://github.com/mozilla/addons-code-manager/issues/438
It moves `CodeView` to a `LinterProvider` implementation and removes unnecessary linter logic from `pages/Browse`. After this, all components are sharing the same linter logic without any duplicated code.
=> Apply LinterProvider to CodeView for code re-use

src/components/App/index.spec.tsx, src/components/App/index.tsx, src/components/App/styles.module.scss, src/configureStore.spec.tsx, src/configureStore.tsx, src/pages/Index/index.tsx, src/reducers/errors.spec.tsx, src/reducers/errors.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes #182
---
The idea is to have a reducer responsible for storing errors. Given that we focus on API errors, the action currently receives an `Error` object and the reducer extracts this message (could be done in a `createInternalError()` function, that's an implementation detail).
Each error gets an ID assigned to it, unique and predictable given that the next ID is stored into the state. Having such IDs and the increment logic into the reducer avoids complicated unique ID generation and multiple errors for the same component. We never decrement the ID to avoid collisions.
Having an ID on each error allows to "hide" them when the user clicks the "close" button. We do not have an automated way of closing such error messages yet. In the future, we could maybe add a `context` prop to an …
=> Add a simple error handling

src/components/CodeView/index.tsx, src/components/DiffView/index.tsx, src/components/LinterMessage/index.spec.tsx, src/components/LinterMessage/index.tsx, src/components/LinterMessage/styles.module.scss, stories/LinterMessage.stories.tsx
Fixes #436 
---
This is another proposal to fix #436.
Unfortunately, I don't know how to reuse the Bootstrap `background-color` without using its HEX code.
=> Improve inlined linter message style

.env
Fixes #477
---
This won't change anything right now, but it is needed to make
authentication work with FxA and the API in -dev (and later, stage and
prod).
=> Use new fxa config

src/reducers/linter.spec.tsx, src/reducers/linter.tsx, src/reducers/users.spec.tsx, src/reducers/users.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes #472 
---
Removed a bunch of TODOs by dispatching `addError()` instead.
Note: I did not change the behavior of the `linter` reducer here: https://github.com/mozilla/addons-code-manager/blob/c77356d60a358b1775dacb627f9f6630974c4773/src/reducers/linter.tsx#L198-L207
=> Dispatch addError() instead of logging an error message

src/api/index.spec.tsx, src/api/index.tsx, src/components/LoginButton/index.spec.tsx, src/components/LoginButton/index.tsx, src/reducers/linter.spec.tsx, src/reducers/linter.tsx
Fixes #466
Fixes #480 
---
This patch ntroduces a `makeApiURL` function to construct an API URL with common values. Happy to change its name.
=> Create a function to construct an API URL and use it

.env, .env.dev, .env.stage, src/server/index.spec.tsx, src/server/index.tsx
Fixes #421 
---
This _should_ work. When running `yarn start` locally, I see absolute URLs in the HTML and these URLs look good.
Static files are already available on the -dev CDN: http://addons-code-manager-dev-cdn.allizom.org/, so deploying this patch should not be a problem, unless there is a CSP issue. We might loose the `favicon.ico` though 😢
=> Configure a CDN

src/reducers/linter.spec.tsx, src/reducers/linter.tsx
Fixes #490
---
This is safe to land since https://github.com/mozilla/addons-server/issues/11048 has been merged.
It is possible to try this patch in -dev by using Chrome and its "Local Overrides" feature:
=> Pass credentials when fetching the linter results

src/components/LoginButton/index.spec.tsx, src/components/LoginButton/index.tsx
Fixes #486
---
This is needed because the API (which sends the redirect after FxA login page) is not on the same domain, hence a relative URL cannot work. ~~This is not working yet because of an API issue (cf. https://github.com/mozilla/addons-server/issues/11018)~~.
When we use the `local` FxA config, we still want relative URLs because we are using the -dev API for local dev and the API will not allow `localhost:3000` as a valid domain (valid domains are: `code.addons-dev.allizom.org` or `addons-dev.allizom.org`). If we're using the API locally too, then it would recognize `localhost:3000` or `olympia.test` as valid domains, but that would work with relative URLs too so it is much simpler to always pass a relative URL when FxA config is `local`. This also means: the behavior before and …
=> Pass absolute url to api login (fxa)

src/server/index.spec.tsx, src/server/index.tsx
Fixes #423
---
Use real CSP report URLs instead of the no-op one. In local dev, it should still be the no-op endpoint (`/__cspreport__`) but one can build and serve the app (make sure `.env.local` does not contain `REACT_APP_USE_INSECURE_PROXY=true`, then run `yarn build && yarn serve`) to see absolute CSP report URLs.
=> Use existing CSP report URLs

src/server/fixtures/version.json, src/server/index.spec.tsx, src/server/index.tsx
Fixes #428 
---
For the heartbeat endpoint, we do not depend on any service (except the API that has its own heartbeat endpoint already) so that's why both heartbeat and lbheartbeat are the same.
=> Add ops endpoints

src/api/index.spec.tsx, src/api/index.tsx
Fixes #515 
---
I don't know if a new parameter to `callApi` is what we want because only one endpoint will accept credentials and it will fail in all other cases, but it is simpler than re-implementing `callApi` in `logOutFromServer`.
This patch requires https://github.com/mozilla/addons-server/issues/11112 and I want to live-test this change in Chrome before landing this patch, but a quick review is always welcomed :)
=> Add credentials: 'include' to logout call

src/components/FileTree/index.spec.tsx, src/components/FileTree/index.tsx, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/test-helpers.tsx, stories/FileTree.stories.tsx
Fixes #502 
This doesn't actually fix #502, but it's a start. There was a problem before that we were not loading a version into the store, so when `toggleExpandedPath` was dispatched it generated an error. With this patch I can see that `toggleExpandedPath` is succeeding, and that `expandedPaths` in the store is being updated when we click on a folder, but the component isn't responding to that change. So it looks like the `FileTree` component in the story isn't actually connected to the store, even though we're using `renderWithStoreAndRouter`.
Do either of you have any ideas about why that might be?
As an aside, while doing some of this work on `FileTree` I keep running into situations in which it seems to me that it would make more sense to have `FileTree` get its `version` via …
=> Load a version into the store for the FileTree story

src/components/FileTree/index.spec.tsx, src/components/FileTree/index.tsx, src/configureStore.spec.tsx, src/configureStore.tsx, src/reducers/fileTree.spec.tsx, src/reducers/fileTree.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes #533 
This patch moves all of the functionality that creates the `tree` structure out of the `FileTree` component and into a new `fileTree` reducer. This includes:
- The types for `FileNode`, `DirectoryNode` and `TreeNode`.
- The functions `getVersionName`, `getRootPath`, `recursiveSortInPlace` and `buildFileTree`, all of which are used for generating the `tree` and were all moved exactly as is.
- The `FileTree` component now gets its `tree` prop via `mapStateToProps` from the `fileTree` reducer.
- The `FileTree` component now has a `loadData` function which is called from both `componentDidMount` and `componentDidUpdate` which checks whether has a value in the `tree` prop and if not dispatches `fileTreeActions.buildTree`.
- The new `fileTree` reducer exposes one action: `buildTree` …
=> Move buildFileTree into a fileTree reducer

src/components/FileTree/index.spec.tsx, src/components/FileTree/index.tsx, src/reducers/fileTree.spec.tsx, src/reducers/fileTree.tsx
Fixes #538 
This builds a list of file paths that can then be used for keyboard navigation. Note that the `FileTree` component does not currently use the `treePathList` prop, but it does need it to know whether to request that the path list be built by the reducer.
=> Store a list of ordered file paths in the fileTree reducer 

renovate.json
This tells Renovate to send a lockfile maintenance PR once a week (on
Monday). The second added option tells Renovate to wait until branch
tests have passed or failed before opening a PR.
=> Configure lockfile maintenance PRs for Renovate

src/components/App/index.tsx, src/components/FileTree/index.tsx, src/components/LinterProvider/index.tsx, src/components/Navbar/index.tsx, src/components/VersionChooser/index.tsx, src/configureStore.tsx, src/index.tsx, src/pages/Browse/index.tsx, src/pages/Compare/index.tsx, src/reducers/index.tsx, src/test-helpers.tsx
Fixes #275
---
I started from scratch, trying to understand whether CRA officially
supports HMR (hint: it is not as clear as it should be). In the end, I
added some code to enable HMR for React [1] and Redux [2]. It's similar
to what I've done for addons-frontend in the past, albeit much simpler.
Creating `src/reducers/index.tsx` is required so that we can track
changes on all reducers at once.
---
[1]: I tested by live editing a React component, which is updated in FF
without reloading the page. It's hot patched instead
[2]: I tested by adding a new prop to a reducer and it works too (it can
be monitored in the redux devtools)
=> Enable HMR

src/reducers/fileTree.spec.tsx, src/reducers/fileTree.tsx
Fixes #471 
This is just a proof of concept for executing this action which needs data from both the `fileTree` state and the `versions` state, and needs to modify the `versions` state, which I am doing by dispatching `versionActions.updateSelectedPath`. 
I thought I could get away with not having to access `getState` in the thunk, by accepting `currentPath` as a parameter, but we still need it to access the internal state of the `fileTree` reducer, because we also need to dispatch.
I may have gotten a number of things wrong here, because it still seems a bit convoluted to me. Submitting this for feedback on the approach.
@willdurand this is something I discussed with @kumar303 via Vidyo today, but please feel free to comment if you have any suggestions.
=> Create actions for selecting the next and previous file in the tree

src/components/FileTree/index.tsx, src/reducers/fileTree.tsx
Fixes #552 
~~Depends on #547~~
Only the final commit in this PR is relevant to this patch.
Note that this change is being made to simplify the changes required for #459, which will require that the `FileTree` component also have access to `pathList` from the `fileTree` state.
=> The fileTree reducer should not store an empty FileTree object 

src/components/CodeView/index.spec.tsx, src/components/CodeView/index.tsx, src/components/CodeView/utils.spec.tsx, src/components/CodeView/utils.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/546
This seems like a small thing to add a function for but it will help to synchronize the line linking functionality between `Browse` and the forthcoming code overview component (see https://github.com/mozilla/addons-code-manager/pull/542/files#diff-4a3375c826127680658868411c3f42d3R236).
=> Use common functions to get code line anchors

src/components/VersionChooser/index.spec.tsx, src/components/VersionChooser/index.tsx, src/components/VersionSelect/index.spec.tsx, src/components/VersionSelect/index.tsx, src/reducers/versions.tsx, stories/VersionChooser.stories.tsx
Fixes #415
---
Comparisons are strict because I am not sure we want to compare the same old/new version but it is easy to change if needed.
=> Filter old/new versions depending on the selected values

package.json, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/reducers/fileTree.spec.tsx, src/reducers/fileTree.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/utils.spec.tsx, src/utils.tsx, yarn.lock
Fixes #286
~~⚠️ depends on #48~~
---
This patch adds a new `?path` parameter to the query string when a file is selected. It works in all pages, with keyboard navigation and mouse selection. This patch also allows to load a specific file **in the browse page only**.
Note 1: this patch also has a fix for #551 (only browse component)
Note 2: I'll file an issue to add this feature to the Compare page too
=> Add `?path` to query string when selecting a file

src/components/CodeView/index.spec.tsx, src/components/CodeView/index.tsx, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes #593
---
This patch makes sure the query string is kept in the `CodeView` line anchors. It also ensures we can load any file with a specific line selected. Last but not least, when selecting a new file, it removes the `hash` from the URL.
=> Preserve query parameters and hash in CodeView/Browse

stories/setup/config.tsx
This is a minor config change to fix the following annoying Storybook behavior: when loading the page, the "show addons" option is enabled by default and 3/4 of the page is used to display an empty "addons panel". One has to disable the option to show the stories.
=> Do not open the addons panel by default

src/components/VersionSelect/index.tsx, src/components/VersionSelect/styles.module.scss
Fixes #595 
---
Before:
After:
=> Improve contrast in VersionSelect

src/reducers/linter.spec.tsx, src/reducers/linter.tsx
Fixes #591
---
This patch fixes an issue with the `LinterProvider` dispatching too many asynchronous actions.
=> Make sure we run fetchLinterMessages only once

src/components/Skeleton/index.spec.tsx, src/components/Skeleton/index.tsx, src/components/Skeleton/styles.module.scss, src/components/VersionChooser/index.spec.tsx, src/components/VersionChooser/index.tsx, src/components/VersionSelect/index.spec.tsx, src/components/VersionSelect/index.tsx, stories/Skeleton.stories.tsx
Fixes #607 
Fixes #608 
Supports #379
---
This is a very simple `Skeleton` component that should fill the place where it is added. We can iterate if we need to add constraints (like `range` and `minWidth` props) but it's only the beginning of the long journey to fix #379.
The second commit refactors the `VersionChooser` component to see the `Skeleton` in action:
=> Introduce a Skeleton component

src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx
Fixes #590
Fixes #551
~~⚠️ depends on #593~~
---
I found new bugs after having fixed other unrelated bugs and rebased 😞 Now, both `Browse` and `Compare` components have a similar behavior and the keyboard navigation works for both as intended and without any side effect (hopefully).
It seemed easier to fix #551 as part of this patch, but it resulted in a bigger diff than expected. Sorry about that..
=> Compare load file

src/components/FileTree/index.tsx, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/pages/Compare/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes #602
Fixes #556 
---
This patch is similar to the one merged to solve https://github.com/mozilla/addons-code-manager/issues/565. I added a bunch of early returns in the `reducer` (with `log.error` calls and test cases).
=> Dispatch begin/abort actions when fetching a version and avoid infinite fetch/error loop

src/components/FileTreeNode/index.spec.tsx, src/components/FileTreeNode/index.tsx, src/reducers/fileTree.spec.tsx, src/reducers/fileTree.tsx, src/reducers/linter.spec.tsx, src/reducers/linter.tsx
Fixes #609 
I have written a lot of tests for this, testing the various situations that might exist when navigating between messages. I'm not sure if I have too many, not enough, or just the right number of tests, so that's something to check.
There are some paths as yet untested, for example some errors (I think), but I wanted to submit this for an initial review before going any further with it.
I created an internal function called `findRelativeMessageUid`, but I didn't export it and didn't write any tests for it. I think it makes more sense to just write the tests for `getRelativeMessageUid` to test every scenario, rather than a suite of tests for `findRelativeMessageUid` and then also use `findRelativeMessageUid` in the tests for `getRelativeMessageUid`. And yes, I know those names …
=> Create a function to return the Uid of the next/previous message

src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes #626
---
A regression has been recently merged, breaking the `Browse` component when loading a file from the URL. The regression was supposed to fix an issue but introduced a new one. This patch should solve all the known issues:
- it brings the feature back
- it avoids the issue related to too many actions dispatched when updating the selected path
- it prevents the component to enter an infinite loop in case of an error
=> Fix regression in Browse component

src/components/CodeOverview/index.spec.tsx, src/components/CodeOverview/index.tsx, src/components/CodeOverview/styles.module.scss, stories/CodeOverview.stories.tsx, stories/CodeView.stories.tsx, stories/fixtures/long-file-sample.tsx, stories/setup/styles.scss
Fixes https://github.com/mozilla/addons-code-manager/issues/523
Fixes https://github.com/mozilla/addons-code-manager/issues/622
Fixes https://github.com/mozilla/addons-code-manager/issues/665
~~⚠️ depends on https://github.com/mozilla/addons-code-manager/pull/623~~
Storybook sample:
=> Add linter message support to CodeOverview

src/components/App/index.spec.tsx, src/components/App/index.tsx, src/components/App/styles.module.scss, src/components/CodeOverview/styles.module.scss, src/components/CodeView/styles.module.scss, src/components/DiffView/styles.module.scss, src/components/FullscreenGrid/index.spec.tsx, src/components/FullscreenGrid/index.tsx, src/components/FullscreenGrid/styles.module.scss, src/components/LoginButton/index.tsx, src/components/Navbar/index.tsx, src/components/Navbar/styles.module.scss, src/components/VersionChooser/styles.module.scss, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/pages/Index/index.tsx, src/test-helpers.tsx, stories/CodeView.stories.tsx, stories/FullscreenGrid.stories.tsx, stories/setup/styles.scss
Fixes https://github.com/mozilla/addons-code-manager/issues/652
**TODO**: the file tree area is an improvement over master but I'd like to improve it more in https://github.com/mozilla/addons-code-manager/issues/653
Notes:
- I made the Navbar a bit smaller since the header is always present
- I removed borders from some things since the grid panels have borders now
- Everything else looks more or less the same except all screens are in the grid
- I adapted `FullscreenGrid` to make it easier to work with for our specific app
<details>
</details>
<details>
<summary>Screenshots</summary>
</details>
=> Use FullscreenGrid for everything

src/components/CodeOverview/index.spec.tsx, src/components/CodeOverview/index.tsx, src/test-helpers.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/673
I also moved `createFakeRef()` to the helpers file because this will be useful to other components.
=> Do not use a static React ref in CodeOverview

src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes #638
Fixes #628 
---
While the code looked nice and the test suite was covering all the branches, it appears that most of the code was not needed because loading a file from the URL is done by `fetchDiff`, which takes an optional `path`. Given that there is no URL update triggered by our code, the URL stayed the same and everything just worked as intended. This was nice but complicated and not needed, so I removed it.
The fix for the infinite loop is mostly in `src/reducers/versions.tsx`. Because we load a file, we should abort this action too in case of an error. This allows the `loadData()` method to check the status of the `version` prop.
I added some commits to fix #628 too. I believe it works (i.e. I cannot trigger an infinite loop) but the UI sometimes lags. I covered the …
=> Fix infinite loops in compare page

src/components/ImageView/index.spec.tsx, src/components/ImageView/index.tsx, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/server/index.spec.tsx, src/server/index.tsx, src/test-helpers.tsx, stories/ImageView.stories.tsx
Fixes #109 
A couple of notes:
1. I had to modify the CSP in order to display images from `data:` URLs. I'm not sure if what I did is okay and entirely safe.
2. I only implemented this for the `Browse` page. I don't think it makes sense for the `Compare` page, because if an image was changed I imagine we'd just have a diff of the contents of the file, not a diff showing us two different images, and therefore that wouldn't really be useful to display.
=> View an image file

src/components/DiffView/index.tsx, src/components/DiffView/styles.module.scss, src/components/VersionChooser/index.spec.tsx, src/components/VersionChooser/index.tsx, src/components/VersionChooser/styles.module.scss, src/components/VersionSelect/index.spec.tsx, src/components/VersionSelect/index.tsx, src/components/VersionSelect/styles.module.scss, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/pages/Compare/styles.module.scss, src/reducers/versions.tsx, stories/DiffView.stories.tsx, stories/setup/styles.scss
Fixes https://github.com/mozilla/addons-code-manager/issues/679
Additionally, I associated labels and dropdowns for accessibility.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> Condense version compare dropdowns, make sticky

stories/CodeView.stories.tsx, stories/setup/styles.scss
Fixes https://github.com/mozilla/addons-code-manager/issues/692
The story now uses a grid like the real app. Example:
=> Make CodeView stories look closer to the real app

src/components/FileMetadata/index.tsx, src/components/FileTree/index.spec.tsx, src/components/FileTree/index.tsx, src/components/FileTree/styles.module.scss, src/components/FileTreeNode/styles.module.scss, src/components/FullscreenGrid/index.tsx, src/components/KeyboardShortcuts/index.spec.tsx, src/components/KeyboardShortcuts/index.tsx, src/components/KeyboardShortcuts/styles.module.scss, src/components/VersionFileViewer/index.spec.tsx, src/components/VersionFileViewer/index.tsx, src/components/VersionFileViewer/styles.module.scss, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/pages/Browse/styles.module.scss, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/test-helpers.tsx, stories/FileTreeNode.stories.tsx, stories/setup/styles.scss
Fixes https://github.com/mozilla/addons-code-manager/issues/653
**NOTE**: in attempt to keep the patch small (ha), I deferred these tasks: 
- Decouple KeyboardShortcuts: https://github.com/mozilla/addons-code-manager/issues/678
- Fix hidden file menu issues: https://github.com/mozilla/addons-code-manager/issues/680
<details>
</details>
The compare page works, too, but I think it needs this tweak: https://github.com/mozilla/addons-code-manager/issues/679
=> Use AccordionMenu for files, info, key shortcuts

src/api/index.spec.tsx, src/api/index.tsx
Fixes #164
Fixes #666 😈 
---
You can try this patch by browsing: http://localhost:3000/en-US/browse/616714/versions/1688036/?path=%3Cscript%3Ealert%281%29%3B
=> Format query params sent to the API

.env.olympia, README.md, package.json, src/components/LoginButton/index.spec.tsx, src/components/LoginButton/index.tsx
Fixes #710
---
This is a proposal to add a new env to code-manager that we can use with addons-server. I have been using this env for a while, then it broke because of the API version change (fixed in https://github.com/mozilla/addons-nginx/pull/11) today, so I fixed it and I am proposing it here now.
You can test it by installing addons-server and running `yarn olympia` in code-manager after that. Hopefully the added instructions are clear enough :)
=> Add an env to use code-manager with a local olympia instance

src/components/App/index.spec.tsx, src/components/App/index.tsx, src/components/FullscreenGrid/ContentShell.spec.tsx, src/components/FullscreenGrid/ContentShell.tsx, src/components/FullscreenGrid/index.spec.tsx, src/components/FullscreenGrid/index.tsx, src/components/VersionFileViewer/index.spec.tsx, src/components/VersionFileViewer/index.tsx, src/pages/Index/index.tsx, src/test-helpers.tsx, stories/AccordionMenu.stories.tsx, stories/CodeView.stories.tsx, stories/FullscreenGrid.stories.tsx
Fixes #730
---
This patch supports what's described in #721. I kept the `ContentShell`
files in `FullscreenGrid/` because it is strongly coupled.
=> Extract ContentShell component

src/components/FileTree/index.spec.tsx, src/components/FileTree/index.tsx, src/components/FileTreeNode/index.spec.tsx, src/components/FileTreeNode/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/test-helpers.tsx, stories/FileTreeNode.stories.tsx
This fixes https://github.com/mozilla/addons-code-manager/issues/699 by keeping track of focused nodes and only scrolling when they first come into focus.
=> Only scroll/focus a FileTreeNode when necessary

yarn.lock
This fixes the following errors from `yarn audit` by bumping the `fstream` and `tar` versions  (details: https://github.com/sass/node-sass/issues/2625). This did not require a `package.json` change because the new versions are within range of those that depend on them.
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │ …
```
=> Upgrade fstream and tar to fix vulnerabilities

src/components/FileTreeNode/index.spec.tsx, src/components/FileTreeNode/index.tsx, src/components/FileTreeNode/styles.module.scss, src/reducers/fileTree.spec.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/scss/variables.scss, src/test-helpers.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/413
I didn't have time to add a story but we could do that in https://github.com/mozilla/addons-code-manager/issues/431 💳 
Examples, mostly from http://localhost:3000/en-US/compare/616645/versions/1655530...1655531/?path=scripts/background.js
=> Indicate file diff status in FileTreeNode

src/components/FullscreenGrid/ContentShell.spec.tsx, src/components/FullscreenGrid/ContentShell.tsx, src/components/FullscreenGrid/index.spec.tsx, src/components/FullscreenGrid/index.tsx, src/components/FullscreenGrid/styles.module.scss, src/components/ToggleButton/index.spec.tsx, src/components/ToggleButton/index.tsx, stories/FullscreenGrid.stories.tsx
Fixes #736
~~:warning: Depends on #729, #732 and #734~~
---
This patch allows to expand/collapse the main side panel (left panel). We have everything to implement the same feature for the right panel if we want to.
I filed an issue for the style of the buttons already, because I am pretty sure we can do better: https://github.com/mozilla/addons-code-manager/issues/737.
App:
Storybook 1:
Storybook 2:
Regular screens:
Smaller screens:
=> Toggle main side panel

src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx
Closes https://github.com/mozilla/addons-code-manager/issues/813
This makes some minor adjustments to the titles.
Browse example: `Browse DuckDuckGo Plus: 2019.1.31`
Compare example: `Compare Grammarly for Firefox: 123456...234567`
=> Adjust Browse / Compare page titles

src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/776 by always loading version objects when the comparison parameters change.
I also made sure I didn't regress the fix for https://github.com/mozilla/addons-code-manager/issues/592
The root cause of https://github.com/mozilla/addons-code-manager/issues/776 is that the [compare API](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-compare_to-(int-version_id)-) returns a version *as compared to* the base version you give it. This is confusing because the returned object has the same ID but different data like different statuses for each file path.
I'm not totally happy with this solution (my patch) but it seemed like a quick-ish way to fix …
=> Load version objects amidst different comparisons

src/components/KeyboardShortcuts/index.spec.tsx, src/components/KeyboardShortcuts/index.tsx
Fixes #588
---
I reworked the supported keys a bit so that it is easier to know which key does what and adding new keyboard shortcuts should be a matter of adding a new entry to the `supportedKeys` map + add a `case` block in the switch.
I added a bunch of missing test cases too.
=> Add a keyboard shortcut to toggle the main side panel

src/pages/Compare/utils.spec.tsx, src/pages/Compare/utils.tsx, src/reducers/versions.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/859
This will ultimately be used like `getCodeLineAnchor(line)`:
https://github.com/mozilla/addons-code-manager/blob/0f6bb509136231ad035ea0c76c6c3706df6585de/src/components/CodeOverview/index.tsx#L219-L221
You can see the overview working in https://github.com/mozilla/addons-code-manager/pull/865
=> Add a line-to-change map for the CodeOverview

src/components/FileTree/index.spec.tsx, src/components/FileTree/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
=> Hide top-level folder

.snyk, README.md, package.json, yarn.lock
Our use of `mixin-deep` and `set-value` is either for development only or it won't create a problem since user input cannot send any payloads.
More specifically:
- We only use `http-proxy-middleware` for development
- `react-scripts` does not accept user input to trigger an exploit
=> Ignore mixin-deep / set-value security warnings

src/components/CodeOverview/index.spec.tsx, src/components/CodeOverview/index.tsx, src/components/CodeView/utils.tsx, src/components/VersionFileViewer/index.spec.tsx, src/components/VersionFileViewer/index.tsx, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/reducers/versions.tsx
~~⚠️  Depends on https://github.com/mozilla/addons-code-manager/pull/860~~
This fixes https://github.com/mozilla/addons-code-manager/issues/672 by adding a code overview for the newer file (the head version). The overview won't be of the diff but maybe we could do that as a follow-up. It would be harder to make an overview of the diff.
=> Add CodeOverview to the compare page

src/components/VersionFileViewer/index.spec.tsx, src/components/VersionFileViewer/index.tsx, src/pages/Browse/index.tsx, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/647 by always showing file information now that we can (as of https://github.com/mozilla/addons-code-manager/issues/672 and https://github.com/mozilla/addons-code-manager/issues/846).
=> Always show file information

src/components/AccordionMenu/styles.module.scss, src/components/Button/styles.module.scss
Fixes #882 
@kumar303  I used the second approach you mentioned https://github.com/mozilla/addons-code-manager/issues/882#issue-461151755, since moving all transition/transform into `Button` causes a problem with the toggle button (showing scrollbar when clicked). And it may be unwanted to see both push effect (vertical) of button and horizontal move of the side panel.
=> Move button's transition into AccordionMenu

src/reducers/versions.spec.tsx, src/reducers/versions.tsx
This fixes https://github.com/mozilla/addons-code-manager/issues/884 by creating Redux storage for a *current version* and setting it while fetching versions. Other components can use this to access the current version or know when it's still loading.
Historically, we've used prop-drilling to pass a version object to those that need it. This created a problem for `FileTree` because of how React/Redux render caching works. We had to prop drill a `versionId` and create an [awkward mapping](https://github.com/mozilla/addons-code-manager/blob/dc18550b066dbb741cef5712b9a46b9611ecb1cf/src/components/FileTree/index.tsx#L186-L197).
To display general linter messages (https://github.com/mozilla/addons-code-manager/issues/805) and display the add-on name …
=> Store the current version

src/components/KeyboardShortcuts/index.spec.tsx, src/components/KeyboardShortcuts/index.tsx, src/reducers/fileTree.spec.tsx, src/reducers/fileTree.tsx
Fixes #887 
This does not resolve all of the outstanding issues with linter message navigation, but it does fix the STR in #887 by ensuring that `goToRelativeMessage` generates the correct anchor for both the Browse and Compare views.
=> Use createCodeLineAnchorGetter in KeyboardShortcuts to accommodate both browse and compare views

.snyk
The affected packages aren't handling our incoming JSON so this seems safe to ignore. Can someone double check that? I don't see an upstream patch yet but I set the expiry low so we can resolve this soonish.
=> Temporarily ignore lodash prototype pollution

src/components/CodeView/index.spec.tsx, src/components/CodeView/index.tsx, src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/components/GlobalLinterMessages/index.spec.tsx, src/components/GlobalLinterMessages/index.tsx
Fixes #872 
@kumar303 
In refactoring, I found scrolling to linter messages in different files is not work well (Not sure why..) https://github.com/mozilla/addons-code-manager/issues/887#issuecomment-506862273. 
I tested some pages, this refactoring does not change behaviors when navigating between linter messages.
=> create GlobalLinterMessages component #872

src/components/AccordionMenu/index.tsx, src/components/FileTree/index.tsx, src/components/FileTreeNode/index.tsx
Fixes #585 
@willdurand 
I see type hints with `withRouter()`. Should I change it to a type variable like  ` withRouter<PublicProps & Partial<DefaultProps> & RouterProps>`?
https://github.com/mozilla/addons-code-manager/blob/2f803e40135f0c7ffc3275618f7b7bec102c5675/src/components/DiffView/index.tsx#L275
https://github.com/mozilla/addons-code-manager/blob/2f803e40135f0c7ffc3275618f7b7bec102c5675/src/components/KeyboardShortcuts/index.tsx#L277
=> remove TS hint for connect() HOC

src/components/DiffView/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/926
A significant amount of time is spend in `getWidgets()` for large files.
Here's how I created the benchmark below
- Made a production build with `start-local-dev`
- In Chrome, profiled while loading `package-lock.json` from https://code.addons-dev.allizom.org/en-US/compare/495710/versions/1541610...1688333/ 
- Looked at the timing of `getWidgets()`
Before (7.13 seconds)
After (6.12 milleseconds)
=> Speed up getWidgets() in DiffView for large files

src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/utils.spec.tsx, src/utils.tsx
Fixes #914 
This enables option 2 from https://github.com/mozilla/addons-code-manager/issues/914#issuecomment-508554395, allowing any line in the file to be selected and navigating to the next/previous closest diff in the file.
=> Allow getRelativeDiffAnchor to work with an anchor that isn't a diff anchor

src/pages/Compare/utils.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/924
This doesn't make too big of a dent in the slow file loading problem but I noticed building the comparison map was slow and since it's an easy fix, why not?
Here's how I created the benchmark below
- Made a production build with `start-local-dev`
- Manually [turned off highlighting](https://github.com/mozilla/addons-code-manager/blob/d07fbc30e7571dd8d72b8db449de926fac59c2fc/src/components/DiffView/index.tsx#L202)
- In Chrome, profiled while loading `package-lock.json` from https://code.addons-dev.allizom.org/en-US/compare/495710/versions/1541610...1688333/ 
- Looked at the timing of [`createCodeLineAnchorGetter`](https://github.com/mozilla/addons-code-manager/blob/d07fbc30e7571dd8d72b8db449de926fac59c2fc/src/utils.tsx#L69) …
=> Build a comparison map faster for large files

src/components/DiffView/fixtures/minifiedDiff.tsx, src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/components/DiffView/styles.module.scss, stories/DiffView.stories.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/942
~~I chose not to add any UI feedback about the disabled highlighting only because this is probably a temporary feature.~~ (there is UI feedback now)
=> Disable highlighting for long or wide diffs

src/components/CodeOverview/index.spec.tsx, src/components/CodeView/index.spec.tsx, src/components/CodeView/utils.spec.tsx, src/components/CodeView/utils.tsx
=> Return an empty array from getLines when content is empty

stories/CodeOverview.stories.tsx, stories/setup/styles.scss
Fixes https://github.com/mozilla/addons-code-manager/issues/952
This broke a while ago. I keep meaning to fix it.
Before:
After:
=> Render CodeOverview story in a realistic container

src/components/FadableContent/index.spec.tsx, src/components/FadableContent/index.tsx, src/components/FadableContent/styles.module.scss, stories/FadableContent.stories.tsx, stories/setup/styles.scss
Fixes https://github.com/mozilla/addons-code-manager/issues/959
Example from the storybook:
=> Add FadableContent to convey trimmed code

src/components/SlowPageAlert/index.spec.tsx, src/components/SlowPageAlert/index.tsx, src/utils.spec.tsx, src/utils.tsx, stories/SlowPageAlert.stories.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/962
Example:
Also see https://github.com/mozilla/addons-code-manager/pull/951 for more realistic usage.
=> Add a SlowPageAlert to control optimizations

src/components/Navbar/index.spec.tsx, src/components/Navbar/index.tsx, src/components/Navbar/styles.module.scss, src/test-helpers.tsx
Fixes #756
Add-on name would be shown in Navbar (browse mode and compare mode).
=> Show add-on name in top bar

src/components/CodeView/index.spec.tsx, src/components/CodeView/index.tsx
This fixes https://github.com/mozilla/addons-code-manager/issues/947 by trimming code when it's too long and showing an alert about it.
There are **some caveats** listed in https://github.com/mozilla/addons-code-manager/pull/951#issue-298222030 which also apply here.
Large files are trimmed like this:
When scrolled to the bottom of the trim, the alert is shown again:
When clicking the button to allow slow pages, it does a full refresh and shows the alert again (only at the top):
=> Show an alert for slow loading files in CodeView

src/components/DiffView/fixtures/largeDiff.tsx, src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/components/DiffView/styles.module.scss, src/components/Navbar/styles.module.scss, src/components/VersionChooser/styles.module.scss, src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/scss/variables.scss, stories/DiffView.stories.tsx
This fixes https://github.com/mozilla/addons-code-manager/issues/946 by trimming long diffs and showing an alert about it.
~~⚠️ Depends on https://github.com/mozilla/addons-code-manager/pull/950~~
~~⚠️ Depends on https://github.com/mozilla/addons-code-manager/pull/963~~
Caveats:
* If you click on a linter message from the overview but that message isn't on the screen, the message isn't shown. I'd like to address this in a future issue -- ideas welcome for what to do. See https://github.com/mozilla/addons-code-manager/issues/967
* Similarly, if you use keys to navigate to the next message but that message isn't on the screen ... *same as above*. See https://github.com/mozilla/addons-code-manager/issues/967
* Using `<Alert.Link>` makes the page reload but I think this is a better UX at the …
=> Trim slow diffs and show an alert about it﻿﻿﻿

src/components/Navbar/index.tsx, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/pages/Index/index.spec.tsx, src/pages/Index/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
=> Allow current version id to be false

.snyk
This continues to ignore the [lodash vulnerability](https://snyk.io/vuln/SNYK-JS-LODASH-450202) since none of the affected packages handle user input.
Here is the output of `yarn why lodash` showing everywhere it's used:
<details>
<summary>Output</summary>
```
yarn why v1.17.3
[1/4] Why do we have the module "lodash"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
info 
=> Found "lodash@4.17.11"
info Reasons this module exists
- "http-proxy-middleware" depends on it
- Hoisted from "http-proxy-middleware#lodash"
- Hoisted from "inquirer#lodash"
- Hoisted from "node-sass#lodash"
- Hoisted from "@babel#core#lodash"
- Hoisted from "@storybook#react#lodash"
- Hoisted from "snyk#lodash"
- Hoisted from "snyk#snyk-mvn-plugin#lodash"
- Hoisted …
```
=> Continue ignoring lodash vulnerability; no user input can exploit it

stories/FileTree.stories.tsx, stories/setup/styles.scss
Fixes #431 
<details><summary>Screenshot</summary>
</details>
We have to adjust the browser size to see the long file name truncated. I am not sure if  I should limit the width of the FileTree like this.
<details><summary> Patch </summary>
``` diff
diff --git a/stories/FileTree.stories.tsx b/stories/FileTree.stories.tsx
index ef3aede..c8bce15 100644
--- a/stories/FileTree.stories.tsx
+++ b/stories/FileTree.stories.tsx
@@ -176,4 +176,6 @@ const render = ({ ...moreProps }: Partial<FileTreeProps> = {}) => {
return renderWithStoreAndRouter(<FileTree {...props} />, { store });
};
-storiesOf('FileTree', module).add('default', () => render());
+storiesOf('FileTree', module).add('default', () => {
+  return <div className='FileTreeStory-container'> {render()}</div>;
+});
diff --git …
```
=> Update storybook for file trees

src/api/index.tsx, src/reducers/comments.spec.tsx, src/reducers/comments.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/988
~~⚠️ This depends on https://github.com/mozilla/addons-code-manager/pull/1040~~
@bobsilverberg I removed the type safety around accepting `comment` or `cannedResponseId` because I ran into errors. I'd need to switch the params to [discriminated unions](https://basarat.gitbooks.io/typescript/docs/types/discriminated-unions.html) to fix it; I don't think that's worth it. For example, I'd need to add a literal `type` field so that one call has `{ type: 'COMMENT' }` and the other has `{ type: 'CANNED_COMMENT' }`.
=> Adds a thunk for creating / updating a comment

src/components/KeyboardShortcuts/index.spec.tsx, src/test-helpers.tsx
Fixes #1046 
The removes the `UnhandledPromiseRejectionWarning`s and also fixes the test failures that came from just using plain `jest` stubs. I'm not sure if this is the correct or proper fix, though, so feedback is appreciated.
=> Fix problem generating UnhandledPromiseRejectionWarnings

src/components/Comment/index.spec.tsx, src/components/Comment/index.tsx, src/components/CommentList/index.spec.tsx, src/components/CommentList/index.tsx, src/components/CommentList/styles.module.scss, src/reducers/comments.tsx, src/test-helpers.tsx, stories/CommentList.stories.tsx, stories/setup/styles.scss
Fixes https://github.com/mozilla/addons-code-manager/issues/1054
This will be used in `CodeView` to show code comments inline (and in other places later). Here is an example from the storybook:
=> Add a CommentList component

.env, .env.dev, src/components/CodeView/index.spec.tsx, src/components/CodeView/index.tsx, src/components/CodeView/styles.module.scss, src/components/CommentList/index.tsx, src/components/Commentable/index.tsx, src/test-helpers.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/112
This is the first patch where I can land an actual UI for adding a comment 🎸 🥁 🎹 🔥 🎵 
It will require a config flag which is off everywhere except the local development server. (**TODO**: file a PR to turn it on for the hosted dev site.)
This will only allow you to enter a comment and see it on the page. It *is* saved via the API but if you refresh the page you won't see the comment (that will happen later).
<details>
</details>
=> Support commenting on a line of a file

yarn.lock
This upgrades all sub-deps of react-scripts.
The main goal is to upgrade handlebars [for this security bug](https://app.snyk.io/org/add-ons-team/project/699db451-28cc-4485-b6cf-70e220c2f09c) but AFAIK there is no way to tell yarn just to upgrade handlebars as a sub dependency (see https://github.com/yarnpkg/yarn/issues/4986). 
The security exploit in handlebars is actually not exploitable here because it's only used for istanbul coverage reports which we don't use (we use codecov).
=> Upgrade all sub-deps of react-scripts (to upgrade handlebars)

src/components/CommentList/index.spec.tsx, src/components/CommentList/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/713
The `CommentList` component gets rendered for every single line in a file. If that line doesn't have comments, it renders `null`. `CommentList` will lazily dispatch a loader (a thunk) *once*. I think performance-wise it's fine because nothing gets dispatched until the thunk starts running and the thunk returns early in case a load is in progress. 
I chose to put the loader here only because this is the component that depends on comments. In the future, more components might depend on loaded comments so we could move it to a shared `<WithLoadedComments>` provider or something.
=> Render saved comments in Browse mode

src/api/index.spec.tsx, src/api/index.tsx, src/reducers/linter.spec.tsx, src/test-helpers.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1114
=> Add deleteComment() API and support DELETE responses better

src/components/App/index.spec.tsx, src/components/App/index.tsx, src/components/LoginButton/index.spec.tsx, src/components/LoginButton/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1139
Now, when loading, the navbar is shown with a disabled login button.
<details>
<summary>Screenshot</summary>
</details>
=> Always show the top NavBar

src/components/Comment/index.spec.tsx, src/components/Comment/index.tsx, src/components/Comment/styles.module.scss
Fixes https://github.com/mozilla/addons-code-manager/issues/1147 by left-aligning the delete button and fixes https://github.com/mozilla/addons-code-manager/issues/1149 by adjusting the prompt.
I also added a `border-radius` to comments so they're more consistent with other app panels.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> Left-align delete button, improve confirm prompt

src/components/Navbar/index.spec.tsx, src/components/Navbar/index.tsx, src/components/Navbar/styles.module.scss, src/scss/variables.scss, src/test-helpers.tsx, stories/Navbar.stories.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/114
Notes
- This is a quick implementation of enabling reviewers to finish a review. They will have to copy / paste the text but at least it's a start.
- This is not hidden behind a config flag because comments will [never get loaded](https://github.com/mozilla/addons-code-manager/blob/6c62fb989785ee0802f41a961f3cf27e784b7f74/src/components/CodeView/index.tsx#L194-L207) unless the config flag is enabled.
<details>
<summary>Example screenshots</summary>
</details>
=> Add Navbar actions to summarize all comments

package.json, yarn.lock
Reverts mozilla/addons-code-manager#1179 because of https://github.com/andreypopp/react-textarea-autosize/issues/253
=> Revert "Update dependency react-textarea-autosize to v7.1.1"

src/api/index.spec.tsx, src/api/index.tsx, src/reducers/comments.spec.tsx, src/reducers/comments.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1093
Example of loading more than 25 saved comments:
=> Load all API pages when fetching saved comments

src/components/CodeView/index.tsx, src/components/CodeView/styles.module.scss, stories/CodeView.stories.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/997
This renders code lines as `pre-wrap` (just like `DiffView`) which lets the comment box span the view port in a sane way.
**Before**
**After**
=> Wrap long CodeView lines to fix comment boxes

src/components/Button/styles.module.scss, src/components/Commentable/styles.module.scss, src/components/SidePanel/styles.module.scss
Fixes https://github.com/mozilla/addons-code-manager/issues/1198
This addresses a few other issues related to the same problem.
**Before**
**After**
=> Increase specificity to make gray buttons gray

.gitignore
Since it's not clear that `.vscode` files would ever need to be checked in, let's encourage devs to ignore them globally rather than explicitly in the shared ignore file. This patch reverts some changes from https://github.com/mozilla/addons-code-manager/pull/1210 after feedback.
=> Encourage devs to ignore .vscode globally

src/components/Comment/styles.module.scss, stories/Comment.stories.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1108
I suggest hiding whitespace since I re-organized the comments story a bit.
**Before**
**After**
=> Break long words in rendered comments

src/components/Comment/index.spec.tsx, src/components/Comment/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1106 by not throwing [this error](https://github.com/mozilla/addons-code-manager/blob/980d88413d4457f0b545d2dd413d9195934da6b4/src/api/index.tsx#L411).
After this patch, the UI will let you submit an empty comment until https://github.com/mozilla/addons-server/issues/12865 is fixed. Once that API issue is fixed, the error will show up at the top like other errors. I also confirmed that the comment form will remain open and editable when the error is displayed, allowing the user to correct the mistake and try again.
=> Pass empty comments to the API

src/components/FileTree/index.spec.tsx, src/components/FileTree/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/test-helpers.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1248
This is an attempt to refactor `expandedPaths` out of `version` object in a progressive way according to https://github.com/mozilla/addons-code-manager/pull/1100#issuecomment-549474948
=> Preserve expanded path when selecting new version

.env.common-local, src/components/Navbar/index.spec.tsx, src/components/Navbar/index.tsx, src/components/Navbar/styles.module.scss
Fixes #984 
I wasn't sure whether we wanted a link *added* to the Navbar, or whether we wanted to use the existing label for the add-on name *as* the link back to the reviewer tools, so I did the former. It's easy enough to change this so no new link is added and we simply linkify the existing label. Because I wasn't sure about this, I didn't apply any styling to the new link, which is why it's currently blue. I will fix that if we decide to keep the new link.
Screenshot:
=> Add a link back to Reviewer Tools

src/components/ErrorBoundary/index.spec.tsx, src/components/ErrorBoundary/index.tsx, src/components/ErrorBoundary/styles.module.scss, src/index.tsx, stories/ErrorBoundary.stories.tsx
Fixes #900 
The page that is shown when an error is caught is ugly, but I'm not sure exactly what it should look like. All of the pages on the site currently use the `FullScreenGrid`, but I think this needs to be rendered as a standalone page in order to make sure no errors are thrown during the rendering of the error page.
We can either fix it up to make it prettier now (once we decide what it should look like), or we could make that a follow-up, as I don't think we envision many people ever seeing this page.
I'm also not sure how to create an STR for the error condition being encountered with production settings, but I think we need that to enable QA to test this.
=> Add an ErrorBoundary

src/api/index.spec.tsx, src/api/index.tsx, src/components/App/index.spec.tsx, src/reducers/comments.spec.tsx, src/reducers/linter.spec.tsx, src/reducers/users.spec.tsx, src/reducers/versions.spec.tsx, src/test-helpers.tsx
reference issue #1193
**description:**
Refactor the creation of all {error: Error} objects with the createErrorResponse helper function for all the test cases that use it. Prettier-ed and linted.
**tests checked & passed:**
yarn lint, yarn eslint, yarn typecheck, yarn type-coverage, yarn test
=> Fixes #1193: Add helper for creating an error response

src/components/Navbar/index.spec.tsx, src/components/Navbar/index.tsx, src/components/Navbar/styles.module.scss, src/components/VersionChooser/index.tsx, src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/pages/Index/index.spec.tsx, src/pages/Index/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx, stories/Navbar.stories.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1263
I noticed a few things in the tests that needed cleanup. I tried to exclude those changes but `git add -p` wasn't making it easy. Let me know if you'd rather I postpone the cleanup until later but I don't think it will make the patch much smaller.
Before:
After (while browsing):
After (while comparing versions):
=> Show base / current version indicators in NavBar

src/components/VersionChooser/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes #1094. This is the first patch for #1258.
I copied `selectedPath` and `visibleSelectedPath` out of version object, and changed `VersionChooser` to use these non-version props.
=> Copy selectedPath and visibleSelectedPath out of version object

src/@types/react-diff-view/index.d.ts, src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/components/DiffView/styles.module.scss, src/test-helpers.tsx
Fixes #989 
This allows for commenting on a normal or inserted line, but not a deleted line as there are issues that need to be ironed out on the server side to enable that. An "add comment" button will appear when hovering over the line number, and any comments added will appear underneath the line, just as they do in the browse view.
Screenshot:
=> Comment on a line of a diff

stories/Navbar.stories.tsx
This was a VSCode fail by me in [an earlier patch](https://github.com/mozilla/addons-code-manager/pull/1264/files#diff-172a7e863b4b5dafa7361ffd550cadb0R19), sorry. Other than this I do like the auto-importing feature 😁 😬
=> Remove unnecessary import

src/components/VersionChooser/index.spec.tsx, src/components/VersionChooser/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1278
This allows the reviewer to easily bounce between comparison mode and browse mode.
<details>
</details>
=> Browse a version from the compare popover

src/components/VersionChooser/index.spec.tsx, src/components/VersionChooser/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1306
The bug was that local component state was not synchronized with Redux state properly.
My first attempt was to fix the local state synchronization but it became way too difficult due to the way these two state managers are different (mostly in relation to component lifecycles). 
In the end, it felt easier just to rely exclusively on Redux state. This also will work better with time travel debugging so I'm not sure why I didn't do it this way to begin with.
=> Preserve VersionChooser form selections better

src/components/CodeOverview/index.spec.tsx, src/components/CodeOverview/index.tsx, src/components/CodeView/index.spec.tsx, src/components/CodeView/index.tsx, src/components/CodeView/utils.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/677
I wanted to add a story for this but was blocked by https://github.com/mozilla/addons-code-manager/issues/1315
=> Show global linter messages in overview

src/components/FileTree/index.spec.tsx, src/components/FileTree/index.tsx, src/components/KeyboardShortcuts/index.spec.tsx, src/pages/Browse/index.spec.tsx, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/reducers/fileTree.spec.tsx, src/reducers/fileTree.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes #1261 
The idea is to force the page to fetch and reload a new `version`, then build the file tree again when changing the version number (either base version or head version). I do not like this approach, since it seems to make `FileTree` component less self-contained. But it may be a quick way to fix without disturbing too much.
=> Fix file tree error when changing version number in compare mode

src/components/VersionFileViewer/index.spec.tsx, src/components/VersionFileViewer/index.tsx
Fixes https://github.com/mozilla/addons-code-manager/issues/1334
---
This patch optimizes "cold starts" only because we only fetch the validation information once for a given version (if I am not mistaken). That being said, I can see huge performance boosts when cold loading a large file.
=> Only render the `VersionFileViewer` children when linter messages are loaded

src/components/VersionChooser/index.tsx, stories/VersionChooser.stories.tsx
Fixes #1359 
Since we already wrapped the `VersionChooser` component in `MemoryRouter`, I think we do not need `VersionChooserWithoutRouter` anymore.
=> Fix VersionChooser story

src/components/CodeOverview/index.spec.tsx, src/components/CodeOverview/index.tsx
=> Do not throw an error when clicking empty lines in code overview

src/components/FileTreeNode/index.tsx
Fixes #695 
it looks like an easy fix without using `react-intersection-observer`. The parameter [`scroolIntoViewOptions`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) is not supported well for all browsers, but at least it works well in Firefox and Chrome.
Using 'j' 'k' to change files
=> Ensure file tree list auto-scrolls only when needed

src/components/CodeLineShapes/index.spec.tsx, src/components/CodeLineShapes/index.tsx, src/components/CodeLineShapes/styles.module.scss, src/components/CodeOverview/index.spec.tsx, src/components/CodeOverview/index.tsx, src/components/VersionFileViewer/index.spec.tsx, src/components/VersionFileViewer/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes #920 
This adds an indication for inserted lines into the `CodeOverview` component.
=> Show indication of changed lines in code overview

src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/reducers/versions.tsx, src/utils.tsx
Fixes #1322. I am sure if this approach is desirable.
I found it a bit tricky to use `enum` in this case, because `enum` defined in `@types/react-diff-view/index.d.ts` file [could not be used in other files](https://lukasbehal.com/2017-05-22-enums-in-declaration-files/). Finally I just defined a new `const` in `reducer/version.tsx`.
=> Refactor to avoid hardcoding changeType

src/pages/Browse/index.spec.tsx, src/pages/Browse/index.tsx, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx
Fixes #1421 
The main idea of this patch is to call `fetchVersion` with `{path: undefined}` to get version info (including the file list), so that we can get the updated file tree, even though the selected path does not exist in the new version.
=> Update the file list when switching between Browse and Compare page

src/components/CodeOverview/index.spec.tsx, src/components/CodeOverview/index.tsx
=> Defeat memoization with LinterProvider in CodeOverview to allow it to re-render on state changes

package.json, stories/setup/webpack.config.js
Fixes #1430 
I realized we do have webpack config file for storybook. It looks like the workaround in https://github.com/storybookjs/storybook/issues/9777#issuecomment-584058329 works.
=> Fix storybook build

package.json, src/components/CodeView/index.spec.tsx, src/components/CodeView/index.tsx, src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/utils.spec.tsx, src/utils.tsx
Fixes #1423 
This will send data on the performance of the render function for both `CodeView` and `DiffView` to GA for future analysis. There has been some discussion about how much highlighting affects the performance, so I built in a separate measure of just the highlighting piece for the `CodeView` component.
=> Use React.Profiler to send render timings to GA

src/components/CodeView/index.spec.tsx, src/components/CodeView/index.tsx, src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/utils.spec.tsx, src/utils.tsx
Fixes #1507 
Also makes some changes to the way that trimming works, specifically:
- For non-minified files, trimming is based on number of lines, not number of characters.
- For minified files, trimming is based on number of characters.
=> Change logic for trimming both minified and non-minified code

.env, .env.common-local, src/tracking.spec.tsx, src/tracking.tsx
Fixes #1569 
I also found a bug in the way we were handling boolean values from `env` files in `tracking.tsx` which I fixed.
=> Turn off debug mode for Google Analytics

stories/setup/styles.scss
Fixes https://github.com/mozilla/addons-code-manager/issues/1435
Before:
After:
=> Fix FullscreenGrid story layout

src/components/LinterMessage/index.tsx
Fixes #328 
LinterMessage components now open in a new tab using attributes `target="_blank"` and `rel="noreferrer noopener"`.
=> LinterMessage link open externally

src/@types/react-diff-view/index.d.ts, src/components/DiffView/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
=> Remove references to `oldRevision` and `newRevision` from the code

src/components/FileMetadata/index.spec.tsx, src/components/FileMetadata/index.tsx, src/components/KeyboardShortcuts/index.spec.tsx, src/components/KeyboardShortcuts/index.tsx, src/components/VersionFileViewer/index.spec.tsx, src/components/VersionFileViewer/index.tsx, src/pages/Compare/index.spec.tsx, src/pages/Compare/index.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx, src/test-helpers.tsx, src/utils.spec.tsx, src/utils.tsx
Fixes #1599 
Fixes #1574 
Fixes #1327 
~~Depends on #1646~~
I realize that this is still a huge patch, but I have already spent a lot of time breaking a larger patch into smaller pieces, and I'm not sure I can reduce this one much more, as making the change impacts a lot of other areas. Probably the majority of the changes in this patch are to tests, but I know that doesn't make it any easier to review.
This patch finishes implementing everything we need to do the following:
1. Once a version is loaded, we will only retrieve the diff info for each subsequent file, rather than retrieving the entire version each time.
2. As a side effect of this change, we no longer need to also retrieve the contents of the file for the current version - we can get away with only retrieving the diff.
The …
=> Only retrieve file info when that's all we need, in the Compare view

src/api/index.spec.tsx, src/api/index.tsx, src/components/CodeOverview/index.spec.tsx, src/components/CodeOverview/index.tsx, src/components/CodeView/index.spec.tsx, src/components/CodeView/index.tsx, src/components/DiffView/index.spec.tsx, src/components/DiffView/index.tsx, src/components/FileTreeNode/index.spec.tsx, src/components/FileTreeNode/index.tsx, src/components/LinterProvider/index.spec.tsx, src/components/LinterProvider/index.tsx, src/components/VersionFileViewer/index.spec.tsx, src/components/VersionFileViewer/index.tsx, src/reducers/linter.spec.tsx, src/reducers/linter.tsx, src/reducers/versions.spec.tsx, src/reducers/versions.tsx
Fixes #1631 
Note that in order to make the changes desired for #1631, the following additional changes were made, which make up the bulk of this patch:
- Change `LinterProvider` so that it accepts a `version` property, rather than `versionId` and `validationURL`.
- Change the `fetchLinterMessagesIfNeeded` reducer function so that it accepts a `version` argument, rather than `versionId` and `url`.
- Store a `fileId` as part of the internal `Version` type.
Note that this will need to be rebased after #1646 and #1647 land, and that will be much easier to do that the opposite (land this first and rebase those), so it probably makes sense to hold off on this one until those land.
=> Call validation endpoint the same way we call other APIs

.github/stale.yml
Removes the contrib:welcome label from stalebot exclusions.
=> Remove contrib:welcome exclusion from stalebot

.circleci/config.yml
Fixes https://github.com/mozilla/addons-code-manager/issues/2150
=> Print node version when we build the docker image

Dockerfile
The purpose of this PR is to make it possible to run the docker image as a non-root user.
Fixes #2181
=> Use specific non-root user to run the container

.circleci/config.yml
Relates to https://github.com/mozilla/addons/issues/1565
We don't currently actively maintain this repos but it's best to ensure future builds will work...
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDCDMGR-508)
=> Switch ubuntu image to 2004:current (ubuntu-2004:202201-02 is deprecated)
